/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ExtensionInfo;
import io.swagger.client.model.ServiceInfo;
import io.swagger.client.model.StatusInfo;

/**
 * AccountInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class AccountInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("mainNumber")
  private String mainNumber = null;

  @SerializedName("operator")
  private ExtensionInfo operator = null;

  @SerializedName("partnerId")
  private String partnerId = null;

  @SerializedName("serviceInfo")
  private ServiceInfo serviceInfo = null;

  /**
   * Specifies account configuration wizard state (web service setup). The default value is 'NotStarted'
   */
  public enum SetupWizardStateEnum {
    @SerializedName("NotStarted")
    NOTSTARTED("NotStarted"),
    
    @SerializedName("Incomplete")
    INCOMPLETE("Incomplete"),
    
    @SerializedName("Completed")
    COMPLETED("Completed");

    private String value;

    SetupWizardStateEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("setupWizardState")
  private SetupWizardStateEnum setupWizardState = null;

  /**
   * Status of the current account
   */
  public enum StatusEnum {
    @SerializedName("Confirmed")
    CONFIRMED("Confirmed"),
    
    @SerializedName("Disabled")
    DISABLED("Disabled");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("statusInfo")
  private StatusInfo statusInfo = null;

  public AccountInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of an account
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of an account")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AccountInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Canonical URI of an account
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Canonical URI of an account")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public AccountInfo mainNumber(String mainNumber) {
    this.mainNumber = mainNumber;
    return this;
  }

   /**
   * Main phone number of the current account
   * @return mainNumber
  **/
  @ApiModelProperty(example = "null", value = "Main phone number of the current account")
  public String getMainNumber() {
    return mainNumber;
  }

  public void setMainNumber(String mainNumber) {
    this.mainNumber = mainNumber;
  }

  public AccountInfo operator(ExtensionInfo operator) {
    this.operator = operator;
    return this;
  }

   /**
   * Operator's extension information. This extension will receive all calls and messages intended for the operator
   * @return operator
  **/
  @ApiModelProperty(example = "null", value = "Operator's extension information. This extension will receive all calls and messages intended for the operator")
  public ExtensionInfo getOperator() {
    return operator;
  }

  public void setOperator(ExtensionInfo operator) {
    this.operator = operator;
  }

  public AccountInfo partnerId(String partnerId) {
    this.partnerId = partnerId;
    return this;
  }

   /**
   * Additional account identifier, developed and applied by the client
   * @return partnerId
  **/
  @ApiModelProperty(example = "null", value = "Additional account identifier, developed and applied by the client")
  public String getPartnerId() {
    return partnerId;
  }

  public void setPartnerId(String partnerId) {
    this.partnerId = partnerId;
  }

  public AccountInfo serviceInfo(ServiceInfo serviceInfo) {
    this.serviceInfo = serviceInfo;
    return this;
  }

   /**
   * Account service information, including brand, service plan and billing plan
   * @return serviceInfo
  **/
  @ApiModelProperty(example = "null", value = "Account service information, including brand, service plan and billing plan")
  public ServiceInfo getServiceInfo() {
    return serviceInfo;
  }

  public void setServiceInfo(ServiceInfo serviceInfo) {
    this.serviceInfo = serviceInfo;
  }

  public AccountInfo setupWizardState(SetupWizardStateEnum setupWizardState) {
    this.setupWizardState = setupWizardState;
    return this;
  }

   /**
   * Specifies account configuration wizard state (web service setup). The default value is 'NotStarted'
   * @return setupWizardState
  **/
  @ApiModelProperty(example = "null", value = "Specifies account configuration wizard state (web service setup). The default value is 'NotStarted'")
  public SetupWizardStateEnum getSetupWizardState() {
    return setupWizardState;
  }

  public void setSetupWizardState(SetupWizardStateEnum setupWizardState) {
    this.setupWizardState = setupWizardState;
  }

  public AccountInfo status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the current account
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Status of the current account")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public AccountInfo statusInfo(StatusInfo statusInfo) {
    this.statusInfo = statusInfo;
    return this;
  }

   /**
   * Status information (reason, comment, lifetime). Returned for 'Disabled' status only
   * @return statusInfo
  **/
  @ApiModelProperty(example = "null", value = "Status information (reason, comment, lifetime). Returned for 'Disabled' status only")
  public StatusInfo getStatusInfo() {
    return statusInfo;
  }

  public void setStatusInfo(StatusInfo statusInfo) {
    this.statusInfo = statusInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountInfo accountInfo = (AccountInfo) o;
    return Objects.equals(this.id, accountInfo.id) &&
        Objects.equals(this.uri, accountInfo.uri) &&
        Objects.equals(this.mainNumber, accountInfo.mainNumber) &&
        Objects.equals(this.operator, accountInfo.operator) &&
        Objects.equals(this.partnerId, accountInfo.partnerId) &&
        Objects.equals(this.serviceInfo, accountInfo.serviceInfo) &&
        Objects.equals(this.setupWizardState, accountInfo.setupWizardState) &&
        Objects.equals(this.status, accountInfo.status) &&
        Objects.equals(this.statusInfo, accountInfo.statusInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri, mainNumber, operator, partnerId, serviceInfo, setupWizardState, status, statusInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    mainNumber: ").append(toIndentedString(mainNumber)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    partnerId: ").append(toIndentedString(partnerId)).append("\n");
    sb.append("    serviceInfo: ").append(toIndentedString(serviceInfo)).append("\n");
    sb.append("    setupWizardState: ").append(toIndentedString(setupWizardState)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusInfo: ").append(toIndentedString(statusInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

