/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * BillingPlanInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class BillingPlanInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Duration period
   */
  public enum DurationUnitEnum {
    @SerializedName("Month")
    MONTH("Month"),
    
    @SerializedName("Day")
    DAY("Day");

    private String value;

    DurationUnitEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("durationUnit")
  private DurationUnitEnum durationUnit = null;

  @SerializedName("duration")
  private String duration = null;

  /**
   * Billing plan type
   */
  public enum TypeEnum {
    @SerializedName("Initial")
    INITIAL("Initial"),
    
    @SerializedName("Regular")
    REGULAR("Regular"),
    
    @SerializedName("Suspended")
    SUSPENDED("Suspended"),
    
    @SerializedName("Trial")
    TRIAL("Trial"),
    
    @SerializedName("TrialNoCC")
    TRIALNOCC("TrialNoCC"),
    
    @SerializedName("Free")
    FREE("Free");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  public BillingPlanInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of a billing plan
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a billing plan")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BillingPlanInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Billing plan name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Billing plan name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BillingPlanInfo durationUnit(DurationUnitEnum durationUnit) {
    this.durationUnit = durationUnit;
    return this;
  }

   /**
   * Duration period
   * @return durationUnit
  **/
  @ApiModelProperty(example = "null", value = "Duration period")
  public DurationUnitEnum getDurationUnit() {
    return durationUnit;
  }

  public void setDurationUnit(DurationUnitEnum durationUnit) {
    this.durationUnit = durationUnit;
  }

  public BillingPlanInfo duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Number of duration units
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "Number of duration units")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public BillingPlanInfo type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Billing plan type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "Billing plan type")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingPlanInfo billingPlanInfo = (BillingPlanInfo) o;
    return Objects.equals(this.id, billingPlanInfo.id) &&
        Objects.equals(this.name, billingPlanInfo.name) &&
        Objects.equals(this.durationUnit, billingPlanInfo.durationUnit) &&
        Objects.equals(this.duration, billingPlanInfo.duration) &&
        Objects.equals(this.type, billingPlanInfo.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, durationUnit, duration, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingPlanInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    durationUnit: ").append(toIndentedString(durationUnit)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

