/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Body2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class Body2 {
  @SerializedName("grant_type")
  private String grantType = null;

  @SerializedName("access_token_ttl")
  private Integer accessTokenTtl = null;

  @SerializedName("refresh_token_ttl")
  private Integer refreshTokenTtl = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("extension")
  private String extension = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("scope")
  private String scope = null;

  @SerializedName("endpoint_id")
  private String endpointId = null;

  public Body2 grantType(String grantType) {
    this.grantType = grantType;
    return this;
  }

   /**
   * Must hold password value for Resource Owner Credentials flow. If client application is not authorized by the specified grant_type, response does not contain refresh_token and refresh_token_ttl attributes
   * @return grantType
  **/
  @ApiModelProperty(example = "null", value = "Must hold password value for Resource Owner Credentials flow. If client application is not authorized by the specified grant_type, response does not contain refresh_token and refresh_token_ttl attributes")
  public String getGrantType() {
    return grantType;
  }

  public void setGrantType(String grantType) {
    this.grantType = grantType;
  }

  public Body2 accessTokenTtl(Integer accessTokenTtl) {
    this.accessTokenTtl = accessTokenTtl;
    return this;
  }

   /**
   * Optional. Access token lifetime in seconds; the possible values are from 600 sec (10 min) to 3600 sec (1 hour). The default value is 3600 sec. If the value specified exceeds the default one, the default value is set. If the value specified is less than 600 seconds, the minimum value (600 sec) is set
   * @return accessTokenTtl
  **/
  @ApiModelProperty(example = "null", value = "Optional. Access token lifetime in seconds; the possible values are from 600 sec (10 min) to 3600 sec (1 hour). The default value is 3600 sec. If the value specified exceeds the default one, the default value is set. If the value specified is less than 600 seconds, the minimum value (600 sec) is set")
  public Integer getAccessTokenTtl() {
    return accessTokenTtl;
  }

  public void setAccessTokenTtl(Integer accessTokenTtl) {
    this.accessTokenTtl = accessTokenTtl;
  }

  public Body2 refreshTokenTtl(Integer refreshTokenTtl) {
    this.refreshTokenTtl = refreshTokenTtl;
    return this;
  }

   /**
   * Optional. Refresh token lifetime in seconds. The default value depends on the client application, but as usual it equals to 7 days. If the value specified exceeds the default one, the default value is applied. If client specifies refresh_token_ttl<=0, refresh token is not returned even if the corresponding grant type is supported
   * @return refreshTokenTtl
  **/
  @ApiModelProperty(example = "null", value = "Optional. Refresh token lifetime in seconds. The default value depends on the client application, but as usual it equals to 7 days. If the value specified exceeds the default one, the default value is applied. If client specifies refresh_token_ttl<=0, refresh token is not returned even if the corresponding grant type is supported")
  public Integer getRefreshTokenTtl() {
    return refreshTokenTtl;
  }

  public void setRefreshTokenTtl(Integer refreshTokenTtl) {
    this.refreshTokenTtl = refreshTokenTtl;
  }

  public Body2 username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Phone number linked to account or extension in account in E.164 format with or without leading \"+\" sign
   * @return username
  **/
  @ApiModelProperty(example = "null", value = "Phone number linked to account or extension in account in E.164 format with or without leading \"+\" sign")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public Body2 extension(String extension) {
    this.extension = extension;
    return this;
  }

   /**
   * Optional. Extension short number. If company number is specified as a username, and extension is not specified, the server will attempt to authenticate client as main company administrator
   * @return extension
  **/
  @ApiModelProperty(example = "null", value = "Optional. Extension short number. If company number is specified as a username, and extension is not specified, the server will attempt to authenticate client as main company administrator")
  public String getExtension() {
    return extension;
  }

  public void setExtension(String extension) {
    this.extension = extension;
  }

  public Body2 password(String password) {
    this.password = password;
    return this;
  }

   /**
   * User's password
   * @return password
  **/
  @ApiModelProperty(example = "null", value = "User's password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public Body2 scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Optional. List of API permissions to be used with access token (see Application Permissions). Can be omitted when requesting all permissions defined during the application registration phase
   * @return scope
  **/
  @ApiModelProperty(example = "null", value = "Optional. List of API permissions to be used with access token (see Application Permissions). Can be omitted when requesting all permissions defined during the application registration phase")
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }

  public Body2 endpointId(String endpointId) {
    this.endpointId = endpointId;
    return this;
  }

   /**
   * Optional. Unique identifier of a client application. You can pass it in request according to pattern [a-zA-Z0-9_\\-]{1,64}. Otherwise it is auto-generated by server. The value will be returned in response in both cases
   * @return endpointId
  **/
  @ApiModelProperty(example = "null", value = "Optional. Unique identifier of a client application. You can pass it in request according to pattern [a-zA-Z0-9_\\-]{1,64}. Otherwise it is auto-generated by server. The value will be returned in response in both cases")
  public String getEndpointId() {
    return endpointId;
  }

  public void setEndpointId(String endpointId) {
    this.endpointId = endpointId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body2 body2 = (Body2) o;
    return Objects.equals(this.grantType, body2.grantType) &&
        Objects.equals(this.accessTokenTtl, body2.accessTokenTtl) &&
        Objects.equals(this.refreshTokenTtl, body2.refreshTokenTtl) &&
        Objects.equals(this.username, body2.username) &&
        Objects.equals(this.extension, body2.extension) &&
        Objects.equals(this.password, body2.password) &&
        Objects.equals(this.scope, body2.scope) &&
        Objects.equals(this.endpointId, body2.endpointId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grantType, accessTokenTtl, refreshTokenTtl, username, extension, password, scope, endpointId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body2 {\n");
    
    sb.append("    grantType: ").append(toIndentedString(grantType)).append("\n");
    sb.append("    accessTokenTtl: ").append(toIndentedString(accessTokenTtl)).append("\n");
    sb.append("    refreshTokenTtl: ").append(toIndentedString(refreshTokenTtl)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

