/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ReservePhoneNumberRequestReserveRecord;
import java.util.ArrayList;
import java.util.List;

/**
 * Body16
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class Body16 {
  @SerializedName("records")
  private List<ReservePhoneNumberRequestReserveRecord> records = new ArrayList<ReservePhoneNumberRequestReserveRecord>();

  public Body16 records(List<ReservePhoneNumberRequestReserveRecord> records) {
    this.records = records;
    return this;
  }

  public Body16 addRecordsItem(ReservePhoneNumberRequestReserveRecord recordsItem) {
    this.records.add(recordsItem);
    return this;
  }

   /**
   * Phone numbers to be reserved/un-reserved
   * @return records
  **/
  @ApiModelProperty(example = "null", value = "Phone numbers to be reserved/un-reserved")
  public List<ReservePhoneNumberRequestReserveRecord> getRecords() {
    return records;
  }

  public void setRecords(List<ReservePhoneNumberRequestReserveRecord> records) {
    this.records = records;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body16 body16 = (Body16) o;
    return Objects.equals(this.records, body16.records);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body16 {\n");
    
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

