/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MeetingScheduleInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * Body8
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class Body8 {
  @SerializedName("topic")
  private String topic = null;

  /**
   * Type of a meeting. 'Instant' - meeting that is instantly started as soon as the host creates it; 'Scheduled' - common scheduled meeting; 'Recurring' - a recurring meeting. If the specified meeting type is 'Scheduled' then schedule property is mandatory for request
   */
  public enum MeetingTypeEnum {
    @SerializedName("Scheduled")
    SCHEDULED("Scheduled"),
    
    @SerializedName("Instant")
    INSTANT("Instant"),
    
    @SerializedName("Recurring")
    RECURRING("Recurring");

    private String value;

    MeetingTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("meetingType")
  private MeetingTypeEnum meetingType = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("schedule")
  private MeetingScheduleInfo schedule = null;

  @SerializedName("allowJoinBeforeHost")
  private Boolean allowJoinBeforeHost = null;

  @SerializedName("startHostVideo")
  private Boolean startHostVideo = null;

  @SerializedName("startParticipantsVideo")
  private Boolean startParticipantsVideo = null;

  @SerializedName("audioOptions")
  private List<String> audioOptions = new ArrayList<String>();

  public Body8 topic(String topic) {
    this.topic = topic;
    return this;
  }

   /**
   * Topic of a meeting
   * @return topic
  **/
  @ApiModelProperty(example = "null", value = "Topic of a meeting")
  public String getTopic() {
    return topic;
  }

  public void setTopic(String topic) {
    this.topic = topic;
  }

  public Body8 meetingType(MeetingTypeEnum meetingType) {
    this.meetingType = meetingType;
    return this;
  }

   /**
   * Type of a meeting. 'Instant' - meeting that is instantly started as soon as the host creates it; 'Scheduled' - common scheduled meeting; 'Recurring' - a recurring meeting. If the specified meeting type is 'Scheduled' then schedule property is mandatory for request
   * @return meetingType
  **/
  @ApiModelProperty(example = "null", value = "Type of a meeting. 'Instant' - meeting that is instantly started as soon as the host creates it; 'Scheduled' - common scheduled meeting; 'Recurring' - a recurring meeting. If the specified meeting type is 'Scheduled' then schedule property is mandatory for request")
  public MeetingTypeEnum getMeetingType() {
    return meetingType;
  }

  public void setMeetingType(MeetingTypeEnum meetingType) {
    this.meetingType = meetingType;
  }

  public Body8 password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password required to join a meeting. Max number of characters is 10
   * @return password
  **/
  @ApiModelProperty(example = "null", value = "Password required to join a meeting. Max number of characters is 10")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public Body8 schedule(MeetingScheduleInfo schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Schedule of a meeting
   * @return schedule
  **/
  @ApiModelProperty(example = "null", value = "Schedule of a meeting")
  public MeetingScheduleInfo getSchedule() {
    return schedule;
  }

  public void setSchedule(MeetingScheduleInfo schedule) {
    this.schedule = schedule;
  }

  public Body8 allowJoinBeforeHost(Boolean allowJoinBeforeHost) {
    this.allowJoinBeforeHost = allowJoinBeforeHost;
    return this;
  }

   /**
   * If 'True' then the meeting can be joined and started by any participant (not host only). Supported for the meetings of 'Scheduled' and 'Recurring' type.
   * @return allowJoinBeforeHost
  **/
  @ApiModelProperty(example = "null", value = "If 'True' then the meeting can be joined and started by any participant (not host only). Supported for the meetings of 'Scheduled' and 'Recurring' type.")
  public Boolean getAllowJoinBeforeHost() {
    return allowJoinBeforeHost;
  }

  public void setAllowJoinBeforeHost(Boolean allowJoinBeforeHost) {
    this.allowJoinBeforeHost = allowJoinBeforeHost;
  }

  public Body8 startHostVideo(Boolean startHostVideo) {
    this.startHostVideo = startHostVideo;
    return this;
  }

   /**
   * Enables starting video when host joins the meeting
   * @return startHostVideo
  **/
  @ApiModelProperty(example = "null", value = "Enables starting video when host joins the meeting")
  public Boolean getStartHostVideo() {
    return startHostVideo;
  }

  public void setStartHostVideo(Boolean startHostVideo) {
    this.startHostVideo = startHostVideo;
  }

  public Body8 startParticipantsVideo(Boolean startParticipantsVideo) {
    this.startParticipantsVideo = startParticipantsVideo;
    return this;
  }

   /**
   * Enables starting video when participants join the meeting
   * @return startParticipantsVideo
  **/
  @ApiModelProperty(example = "null", value = "Enables starting video when participants join the meeting")
  public Boolean getStartParticipantsVideo() {
    return startParticipantsVideo;
  }

  public void setStartParticipantsVideo(Boolean startParticipantsVideo) {
    this.startParticipantsVideo = startParticipantsVideo;
  }

  public Body8 audioOptions(List<String> audioOptions) {
    this.audioOptions = audioOptions;
    return this;
  }

  public Body8 addAudioOptionsItem(String audioOptionsItem) {
    this.audioOptions.add(audioOptionsItem);
    return this;
  }

   /**
   * Meeting audio options. Possible values are 'Phone', 'ComputerAudio'
   * @return audioOptions
  **/
  @ApiModelProperty(example = "null", value = "Meeting audio options. Possible values are 'Phone', 'ComputerAudio'")
  public List<String> getAudioOptions() {
    return audioOptions;
  }

  public void setAudioOptions(List<String> audioOptions) {
    this.audioOptions = audioOptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body8 body8 = (Body8) o;
    return Objects.equals(this.topic, body8.topic) &&
        Objects.equals(this.meetingType, body8.meetingType) &&
        Objects.equals(this.password, body8.password) &&
        Objects.equals(this.schedule, body8.schedule) &&
        Objects.equals(this.allowJoinBeforeHost, body8.allowJoinBeforeHost) &&
        Objects.equals(this.startHostVideo, body8.startHostVideo) &&
        Objects.equals(this.startParticipantsVideo, body8.startParticipantsVideo) &&
        Objects.equals(this.audioOptions, body8.audioOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topic, meetingType, password, schedule, allowJoinBeforeHost, startHostVideo, startParticipantsVideo, audioOptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body8 {\n");
    
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    meetingType: ").append(toIndentedString(meetingType)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    allowJoinBeforeHost: ").append(toIndentedString(allowJoinBeforeHost)).append("\n");
    sb.append("    startHostVideo: ").append(toIndentedString(startHostVideo)).append("\n");
    sb.append("    startParticipantsVideo: ").append(toIndentedString(startParticipantsVideo)).append("\n");
    sb.append("    audioOptions: ").append(toIndentedString(audioOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

