/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Body10
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class Body10 {
  /**
   * Read status of a message to be changed. Multiple values are accepted
   */
  public enum ReadStatusEnum {
    @SerializedName("Read")
    READ("Read"),
    
    @SerializedName("Unread")
    UNREAD("Unread");

    private String value;

    ReadStatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("readStatus")
  private ReadStatusEnum readStatus = null;

  public Body10 readStatus(ReadStatusEnum readStatus) {
    this.readStatus = readStatus;
    return this;
  }

   /**
   * Read status of a message to be changed. Multiple values are accepted
   * @return readStatus
  **/
  @ApiModelProperty(example = "null", value = "Read status of a message to be changed. Multiple values are accepted")
  public ReadStatusEnum getReadStatus() {
    return readStatus;
  }

  public void setReadStatus(ReadStatusEnum readStatus) {
    this.readStatus = readStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body10 body10 = (Body10) o;
    return Objects.equals(this.readStatus, body10.readStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(readStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body10 {\n");
    
    sb.append("    readStatus: ").append(toIndentedString(readStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

