/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CallerInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * Body12
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class Body12 {
  @SerializedName("from")
  private CallerInfo from = null;

  @SerializedName("to")
  private List<CallerInfo> to = new ArrayList<CallerInfo>();

  @SerializedName("text")
  private String text = null;

  public Body12 from(CallerInfo from) {
    this.from = from;
    return this;
  }

   /**
   * Sender of an SMS message. The phoneNumber property must be filled to correspond to one of the account phone numbers which is allowed to send SMS
   * @return from
  **/
  @ApiModelProperty(example = "null", value = "Sender of an SMS message. The phoneNumber property must be filled to correspond to one of the account phone numbers which is allowed to send SMS")
  public CallerInfo getFrom() {
    return from;
  }

  public void setFrom(CallerInfo from) {
    this.from = from;
  }

  public Body12 to(List<CallerInfo> to) {
    this.to = to;
    return this;
  }

  public Body12 addToItem(CallerInfo toItem) {
    this.to.add(toItem);
    return this;
  }

   /**
   * Receiver of an SMS message. The phoneNumber property must be filled
   * @return to
  **/
  @ApiModelProperty(example = "null", value = "Receiver of an SMS message. The phoneNumber property must be filled")
  public List<CallerInfo> getTo() {
    return to;
  }

  public void setTo(List<CallerInfo> to) {
    this.to = to;
  }

  public Body12 text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Text of a message. Max length is 1000 symbols (2-byte UTF-16 encoded). If a character is encoded in 4 bytes in UTF-16 it is treated as 2 characters, thus restricting the maximum message length to 500 symbols
   * @return text
  **/
  @ApiModelProperty(example = "null", value = "Text of a message. Max length is 1000 symbols (2-byte UTF-16 encoded). If a character is encoded in 4 bytes in UTF-16 it is treated as 2 characters, thus restricting the maximum message length to 500 symbols")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body12 body12 = (Body12) o;
    return Objects.equals(this.from, body12.from) &&
        Objects.equals(this.to, body12.to) &&
        Objects.equals(this.text, body12.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, text);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body12 {\n");
    
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

