/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * BusinessAddressInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class BusinessAddressInfo {
  @SerializedName("country")
  private String country = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("street")
  private String street = null;

  @SerializedName("zip")
  private String zip = null;

  public BusinessAddressInfo country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Name of a country
   * @return country
  **/
  @ApiModelProperty(example = "null", value = "Name of a country")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public BusinessAddressInfo state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Name of a state/province
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "Name of a state/province")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public BusinessAddressInfo city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Name of a city
   * @return city
  **/
  @ApiModelProperty(example = "null", value = "Name of a city")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public BusinessAddressInfo street(String street) {
    this.street = street;
    return this;
  }

   /**
   * Street address
   * @return street
  **/
  @ApiModelProperty(example = "null", value = "Street address")
  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public BusinessAddressInfo zip(String zip) {
    this.zip = zip;
    return this;
  }

   /**
   * Zip code
   * @return zip
  **/
  @ApiModelProperty(example = "null", value = "Zip code")
  public String getZip() {
    return zip;
  }

  public void setZip(String zip) {
    this.zip = zip;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessAddressInfo businessAddressInfo = (BusinessAddressInfo) o;
    return Objects.equals(this.country, businessAddressInfo.country) &&
        Objects.equals(this.state, businessAddressInfo.state) &&
        Objects.equals(this.city, businessAddressInfo.city) &&
        Objects.equals(this.street, businessAddressInfo.street) &&
        Objects.equals(this.zip, businessAddressInfo.zip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, state, city, street, zip);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessAddressInfo {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

