/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DeliveryMode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class DeliveryMode {
  /**
   * Notifications transportation provider name. 'APNS' (Apple Push Notifications Service)
   */
  public enum TransportTypeEnum {
    @SerializedName("PubNub")
    PUBNUB("PubNub"),
    
    @SerializedName("APNS")
    APNS("APNS"),
    
    @SerializedName("PubNub/APNS/VoIP")
    PUBNUB_APNS_VOIP("PubNub/APNS/VoIP");

    private String value;

    TransportTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("transportType")
  private TransportTypeEnum transportType = null;

  @SerializedName("encryption")
  private Boolean encryption = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("subscriberKey")
  private String subscriberKey = null;

  @SerializedName("secretKey")
  private String secretKey = null;

  @SerializedName("encryptionAlgorithm")
  private String encryptionAlgorithm = null;

  @SerializedName("encryptionKey")
  private String encryptionKey = null;

  public DeliveryMode transportType(TransportTypeEnum transportType) {
    this.transportType = transportType;
    return this;
  }

   /**
   * Notifications transportation provider name. 'APNS' (Apple Push Notifications Service)
   * @return transportType
  **/
  @ApiModelProperty(example = "null", value = "Notifications transportation provider name. 'APNS' (Apple Push Notifications Service)")
  public TransportTypeEnum getTransportType() {
    return transportType;
  }

  public void setTransportType(TransportTypeEnum transportType) {
    this.transportType = transportType;
  }

  public DeliveryMode encryption(Boolean encryption) {
    this.encryption = encryption;
    return this;
  }

   /**
   * Optional parameter. Specifies if the message will be encrypted or not. For APNS transport type the value is always \"false\"
   * @return encryption
  **/
  @ApiModelProperty(example = "null", value = "Optional parameter. Specifies if the message will be encrypted or not. For APNS transport type the value is always \"false\"")
  public Boolean getEncryption() {
    return encryption;
  }

  public void setEncryption(Boolean encryption) {
    this.encryption = encryption;
  }

  public DeliveryMode address(String address) {
    this.address = address;
    return this;
  }

   /**
   * PubNub channel name. For APNS transport type - internal identifier of a device \"device_token\"
   * @return address
  **/
  @ApiModelProperty(example = "null", value = "PubNub channel name. For APNS transport type - internal identifier of a device \"device_token\"")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public DeliveryMode subscriberKey(String subscriberKey) {
    this.subscriberKey = subscriberKey;
    return this;
  }

   /**
   * PubNub subscriber credentials required to subscribe to the channel
   * @return subscriberKey
  **/
  @ApiModelProperty(example = "null", value = "PubNub subscriber credentials required to subscribe to the channel")
  public String getSubscriberKey() {
    return subscriberKey;
  }

  public void setSubscriberKey(String subscriberKey) {
    this.subscriberKey = subscriberKey;
  }

  public DeliveryMode secretKey(String secretKey) {
    this.secretKey = secretKey;
    return this;
  }

   /**
   * PubNub subscriber credentials required to subscribe to the channel. Optional (for PubNub transport type only)
   * @return secretKey
  **/
  @ApiModelProperty(example = "null", value = "PubNub subscriber credentials required to subscribe to the channel. Optional (for PubNub transport type only)")
  public String getSecretKey() {
    return secretKey;
  }

  public void setSecretKey(String secretKey) {
    this.secretKey = secretKey;
  }

  public DeliveryMode encryptionAlgorithm(String encryptionAlgorithm) {
    this.encryptionAlgorithm = encryptionAlgorithm;
    return this;
  }

   /**
   * Encryption algorithm 'AES' (for PubNub transport type only)
   * @return encryptionAlgorithm
  **/
  @ApiModelProperty(example = "null", value = "Encryption algorithm 'AES' (for PubNub transport type only)")
  public String getEncryptionAlgorithm() {
    return encryptionAlgorithm;
  }

  public void setEncryptionAlgorithm(String encryptionAlgorithm) {
    this.encryptionAlgorithm = encryptionAlgorithm;
  }

  public DeliveryMode encryptionKey(String encryptionKey) {
    this.encryptionKey = encryptionKey;
    return this;
  }

   /**
   * Key for notification message decryption (for PubNub transport type only)
   * @return encryptionKey
  **/
  @ApiModelProperty(example = "null", value = "Key for notification message decryption (for PubNub transport type only)")
  public String getEncryptionKey() {
    return encryptionKey;
  }

  public void setEncryptionKey(String encryptionKey) {
    this.encryptionKey = encryptionKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryMode deliveryMode = (DeliveryMode) o;
    return Objects.equals(this.transportType, deliveryMode.transportType) &&
        Objects.equals(this.encryption, deliveryMode.encryption) &&
        Objects.equals(this.address, deliveryMode.address) &&
        Objects.equals(this.subscriberKey, deliveryMode.subscriberKey) &&
        Objects.equals(this.secretKey, deliveryMode.secretKey) &&
        Objects.equals(this.encryptionAlgorithm, deliveryMode.encryptionAlgorithm) &&
        Objects.equals(this.encryptionKey, deliveryMode.encryptionKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transportType, encryption, address, subscriberKey, secretKey, encryptionAlgorithm, encryptionKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryMode {\n");
    
    sb.append("    transportType: ").append(toIndentedString(transportType)).append("\n");
    sb.append("    encryption: ").append(toIndentedString(encryption)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    subscriberKey: ").append(toIndentedString(subscriberKey)).append("\n");
    sb.append("    secretKey: ").append(toIndentedString(secretKey)).append("\n");
    sb.append("    encryptionAlgorithm: ").append(toIndentedString(encryptionAlgorithm)).append("\n");
    sb.append("    encryptionKey: ").append(toIndentedString(encryptionKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

