/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DepartmentInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class DepartmentInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("extensionNumber")
  private String extensionNumber = null;

  public DepartmentInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of a department extension
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a department extension")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DepartmentInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Canonical URI of a department extension
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Canonical URI of a department extension")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public DepartmentInfo extensionNumber(String extensionNumber) {
    this.extensionNumber = extensionNumber;
    return this;
  }

   /**
   * Number of a department extension
   * @return extensionNumber
  **/
  @ApiModelProperty(example = "null", value = "Number of a department extension")
  public String getExtensionNumber() {
    return extensionNumber;
  }

  public void setExtensionNumber(String extensionNumber) {
    this.extensionNumber = extensionNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepartmentInfo departmentInfo = (DepartmentInfo) o;
    return Objects.equals(this.id, departmentInfo.id) &&
        Objects.equals(this.uri, departmentInfo.uri) &&
        Objects.equals(this.extensionNumber, departmentInfo.extensionNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri, extensionNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepartmentInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    extensionNumber: ").append(toIndentedString(extensionNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

