/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DepartmentResponseExtensionInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class DepartmentResponseExtensionInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("extensionNumber")
  private String extensionNumber = null;

  @SerializedName("partnerId")
  private String partnerId = null;

  public DepartmentResponseExtensionInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of an extension
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of an extension")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DepartmentResponseExtensionInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Canonical URI of an extension
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Canonical URI of an extension")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public DepartmentResponseExtensionInfo extensionNumber(String extensionNumber) {
    this.extensionNumber = extensionNumber;
    return this;
  }

   /**
   * Number of department extension
   * @return extensionNumber
  **/
  @ApiModelProperty(example = "null", value = "Number of department extension")
  public String getExtensionNumber() {
    return extensionNumber;
  }

  public void setExtensionNumber(String extensionNumber) {
    this.extensionNumber = extensionNumber;
  }

  public DepartmentResponseExtensionInfo partnerId(String partnerId) {
    this.partnerId = partnerId;
    return this;
  }

   /**
   * For Partner Applications Internal identifier of an extension created by partner. The RingCentral supports the mapping of accounts and stores the corresponding account ID/extension ID for each partner ID of a client application. In request URIs partner IDs are accepted instead of regular RingCentral native IDs as path parameters using pid = XXX clause. Though in response URIs contain the corresponding account IDs and extension IDs. In all request and response bodies these values are reflected via partnerId attributes of account and extension
   * @return partnerId
  **/
  @ApiModelProperty(example = "null", value = "For Partner Applications Internal identifier of an extension created by partner. The RingCentral supports the mapping of accounts and stores the corresponding account ID/extension ID for each partner ID of a client application. In request URIs partner IDs are accepted instead of regular RingCentral native IDs as path parameters using pid = XXX clause. Though in response URIs contain the corresponding account IDs and extension IDs. In all request and response bodies these values are reflected via partnerId attributes of account and extension")
  public String getPartnerId() {
    return partnerId;
  }

  public void setPartnerId(String partnerId) {
    this.partnerId = partnerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepartmentResponseExtensionInfo departmentResponseExtensionInfo = (DepartmentResponseExtensionInfo) o;
    return Objects.equals(this.id, departmentResponseExtensionInfo.id) &&
        Objects.equals(this.uri, departmentResponseExtensionInfo.uri) &&
        Objects.equals(this.extensionNumber, departmentResponseExtensionInfo.extensionNumber) &&
        Objects.equals(this.partnerId, departmentResponseExtensionInfo.partnerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri, extensionNumber, partnerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepartmentResponseExtensionInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    extensionNumber: ").append(toIndentedString(extensionNumber)).append("\n");
    sb.append("    partnerId: ").append(toIndentedString(partnerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

