/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DialingPlanCountryInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class DialingPlanCountryInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("callingCode")
  private String callingCode = null;

  @SerializedName("isoCode")
  private String isoCode = null;

  @SerializedName("name")
  private String name = null;

  public DialingPlanCountryInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of a country
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a country")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DialingPlanCountryInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Canonical URI of a country
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Canonical URI of a country")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public DialingPlanCountryInfo callingCode(String callingCode) {
    this.callingCode = callingCode;
    return this;
  }

   /**
   * Country calling code defined by ITU-T recommendations E.123 and E.164, see Calling Codes
   * @return callingCode
  **/
  @ApiModelProperty(example = "null", value = "Country calling code defined by ITU-T recommendations E.123 and E.164, see Calling Codes")
  public String getCallingCode() {
    return callingCode;
  }

  public void setCallingCode(String callingCode) {
    this.callingCode = callingCode;
  }

  public DialingPlanCountryInfo isoCode(String isoCode) {
    this.isoCode = isoCode;
    return this;
  }

   /**
   * Country code according to the ISO standard, see ISO 3166
   * @return isoCode
  **/
  @ApiModelProperty(example = "null", value = "Country code according to the ISO standard, see ISO 3166")
  public String getIsoCode() {
    return isoCode;
  }

  public void setIsoCode(String isoCode) {
    this.isoCode = isoCode;
  }

  public DialingPlanCountryInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Official name of a country
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Official name of a country")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DialingPlanCountryInfo dialingPlanCountryInfo = (DialingPlanCountryInfo) o;
    return Objects.equals(this.id, dialingPlanCountryInfo.id) &&
        Objects.equals(this.uri, dialingPlanCountryInfo.uri) &&
        Objects.equals(this.callingCode, dialingPlanCountryInfo.callingCode) &&
        Objects.equals(this.isoCode, dialingPlanCountryInfo.isoCode) &&
        Objects.equals(this.name, dialingPlanCountryInfo.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri, callingCode, isoCode, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DialingPlanCountryInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    callingCode: ").append(toIndentedString(callingCode)).append("\n");
    sb.append("    isoCode: ").append(toIndentedString(isoCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

