/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ExtensionServiceFeatureInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class ExtensionServiceFeatureInfo {
  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("featureName")
  private String featureName = null;

  @SerializedName("reason")
  private String reason = null;

  public ExtensionServiceFeatureInfo enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Feature status; shows feature availability for an extension
   * @return enabled
  **/
  @ApiModelProperty(example = "null", value = "Feature status; shows feature availability for an extension")
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public ExtensionServiceFeatureInfo featureName(String featureName) {
    this.featureName = featureName;
    return this;
  }

   /**
   * Feature name, see all available values in Service Feature List
   * @return featureName
  **/
  @ApiModelProperty(example = "null", value = "Feature name, see all available values in Service Feature List")
  public String getFeatureName() {
    return featureName;
  }

  public void setFeatureName(String featureName) {
    this.featureName = featureName;
  }

  public ExtensionServiceFeatureInfo reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Reason of limitation for a particular service feature. Returned only if the enabled parameter value is 'False', see Service Feature Limitations and Reasons. When retrieving service features for an extension, the reasons for the limitations, if any, are returned in response
   * @return reason
  **/
  @ApiModelProperty(example = "null", value = "Reason of limitation for a particular service feature. Returned only if the enabled parameter value is 'False', see Service Feature Limitations and Reasons. When retrieving service features for an extension, the reasons for the limitations, if any, are returned in response")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtensionServiceFeatureInfo extensionServiceFeatureInfo = (ExtensionServiceFeatureInfo) o;
    return Objects.equals(this.enabled, extensionServiceFeatureInfo.enabled) &&
        Objects.equals(this.featureName, extensionServiceFeatureInfo.featureName) &&
        Objects.equals(this.reason, extensionServiceFeatureInfo.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, featureName, reason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtensionServiceFeatureInfo {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    featureName: ").append(toIndentedString(featureName)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

