/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ExtensionInfoRequestContactInfoRegionalSettingsFormattingLocale;
import io.swagger.client.model.ExtensionInfoRequestContactInfoRegionalSettingsGreetingLanguage;
import io.swagger.client.model.ExtensionInfoRequestContactInfoRegionalSettingsLanguage;
import io.swagger.client.model.ExtensionInfoRequestContactInfoRegionalSettingsTimezone;

/**
 * ExtensionInfoRequestContactInfoRegionalSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class ExtensionInfoRequestContactInfoRegionalSettings {
  @SerializedName("timezone")
  private ExtensionInfoRequestContactInfoRegionalSettingsTimezone timezone = null;

  @SerializedName("language")
  private ExtensionInfoRequestContactInfoRegionalSettingsLanguage language = null;

  @SerializedName("greetingLanguage")
  private ExtensionInfoRequestContactInfoRegionalSettingsGreetingLanguage greetingLanguage = null;

  @SerializedName("formattingLocale")
  private ExtensionInfoRequestContactInfoRegionalSettingsFormattingLocale formattingLocale = null;

  public ExtensionInfoRequestContactInfoRegionalSettings timezone(ExtensionInfoRequestContactInfoRegionalSettingsTimezone timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Timezone data
   * @return timezone
  **/
  @ApiModelProperty(example = "null", value = "Timezone data")
  public ExtensionInfoRequestContactInfoRegionalSettingsTimezone getTimezone() {
    return timezone;
  }

  public void setTimezone(ExtensionInfoRequestContactInfoRegionalSettingsTimezone timezone) {
    this.timezone = timezone;
  }

  public ExtensionInfoRequestContactInfoRegionalSettings language(ExtensionInfoRequestContactInfoRegionalSettingsLanguage language) {
    this.language = language;
    return this;
  }

   /**
   * User interface language data
   * @return language
  **/
  @ApiModelProperty(example = "null", value = "User interface language data")
  public ExtensionInfoRequestContactInfoRegionalSettingsLanguage getLanguage() {
    return language;
  }

  public void setLanguage(ExtensionInfoRequestContactInfoRegionalSettingsLanguage language) {
    this.language = language;
  }

  public ExtensionInfoRequestContactInfoRegionalSettings greetingLanguage(ExtensionInfoRequestContactInfoRegionalSettingsGreetingLanguage greetingLanguage) {
    this.greetingLanguage = greetingLanguage;
    return this;
  }

   /**
   * Information on language used for telephony greetings
   * @return greetingLanguage
  **/
  @ApiModelProperty(example = "null", value = "Information on language used for telephony greetings")
  public ExtensionInfoRequestContactInfoRegionalSettingsGreetingLanguage getGreetingLanguage() {
    return greetingLanguage;
  }

  public void setGreetingLanguage(ExtensionInfoRequestContactInfoRegionalSettingsGreetingLanguage greetingLanguage) {
    this.greetingLanguage = greetingLanguage;
  }

  public ExtensionInfoRequestContactInfoRegionalSettings formattingLocale(ExtensionInfoRequestContactInfoRegionalSettingsFormattingLocale formattingLocale) {
    this.formattingLocale = formattingLocale;
    return this;
  }

   /**
   * Formatting language preferences for numbers, dates and currencies
   * @return formattingLocale
  **/
  @ApiModelProperty(example = "null", value = "Formatting language preferences for numbers, dates and currencies")
  public ExtensionInfoRequestContactInfoRegionalSettingsFormattingLocale getFormattingLocale() {
    return formattingLocale;
  }

  public void setFormattingLocale(ExtensionInfoRequestContactInfoRegionalSettingsFormattingLocale formattingLocale) {
    this.formattingLocale = formattingLocale;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtensionInfoRequestContactInfoRegionalSettings extensionInfoRequestContactInfoRegionalSettings = (ExtensionInfoRequestContactInfoRegionalSettings) o;
    return Objects.equals(this.timezone, extensionInfoRequestContactInfoRegionalSettings.timezone) &&
        Objects.equals(this.language, extensionInfoRequestContactInfoRegionalSettings.language) &&
        Objects.equals(this.greetingLanguage, extensionInfoRequestContactInfoRegionalSettings.greetingLanguage) &&
        Objects.equals(this.formattingLocale, extensionInfoRequestContactInfoRegionalSettings.formattingLocale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timezone, language, greetingLanguage, formattingLocale);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtensionInfoRequestContactInfoRegionalSettings {\n");
    
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    greetingLanguage: ").append(toIndentedString(greetingLanguage)).append("\n");
    sb.append("    formattingLocale: ").append(toIndentedString(formattingLocale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

