/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GreetingLanguageInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class GreetingLanguageInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("localeCode")
  private String localeCode = null;

  @SerializedName("name")
  private String name = null;

  public GreetingLanguageInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of a greeting language
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a greeting language")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GreetingLanguageInfo localeCode(String localeCode) {
    this.localeCode = localeCode;
    return this;
  }

   /**
   * Localization code of a greeting language
   * @return localeCode
  **/
  @ApiModelProperty(example = "null", value = "Localization code of a greeting language")
  public String getLocaleCode() {
    return localeCode;
  }

  public void setLocaleCode(String localeCode) {
    this.localeCode = localeCode;
  }

  public GreetingLanguageInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Official name of a greeting language
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Official name of a greeting language")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GreetingLanguageInfo greetingLanguageInfo = (GreetingLanguageInfo) o;
    return Objects.equals(this.id, greetingLanguageInfo.id) &&
        Objects.equals(this.localeCode, greetingLanguageInfo.localeCode) &&
        Objects.equals(this.name, greetingLanguageInfo.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, localeCode, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GreetingLanguageInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    localeCode: ").append(toIndentedString(localeCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

