/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponseDefault27
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class InlineResponseDefault27 {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("contentUri")
  private String contentUri = null;

  @SerializedName("contentType")
  private String contentType = null;

  @SerializedName("duration")
  private Integer duration = null;

  public InlineResponseDefault27 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of the call recording
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of the call recording")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponseDefault27 contentUri(String contentUri) {
    this.contentUri = contentUri;
    return this;
  }

   /**
   * Link to the call recording binary content
   * @return contentUri
  **/
  @ApiModelProperty(example = "null", value = "Link to the call recording binary content")
  public String getContentUri() {
    return contentUri;
  }

  public void setContentUri(String contentUri) {
    this.contentUri = contentUri;
  }

  public InlineResponseDefault27 contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Call recording file format. Supported format is audio/x-wav
   * @return contentType
  **/
  @ApiModelProperty(example = "null", value = "Call recording file format. Supported format is audio/x-wav")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public InlineResponseDefault27 duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Recorded call duration
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "Recorded call duration")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponseDefault27 inlineResponseDefault27 = (InlineResponseDefault27) o;
    return Objects.equals(this.id, inlineResponseDefault27.id) &&
        Objects.equals(this.contentUri, inlineResponseDefault27.contentUri) &&
        Objects.equals(this.contentType, inlineResponseDefault27.contentType) &&
        Objects.equals(this.duration, inlineResponseDefault27.duration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, contentUri, contentType, duration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponseDefault27 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    contentUri: ").append(toIndentedString(contentUri)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

