/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PersonalContactInfo;
import io.swagger.client.model.SyncInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponseDefault8
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class InlineResponseDefault8 {
  @SerializedName("records")
  private List<PersonalContactInfo> records = new ArrayList<PersonalContactInfo>();

  @SerializedName("syncInfo")
  private SyncInfo syncInfo = null;

  @SerializedName("nextPageId")
  private Integer nextPageId = null;

  @SerializedName("nextPageUri")
  private String nextPageUri = null;

  public InlineResponseDefault8 records(List<PersonalContactInfo> records) {
    this.records = records;
    return this;
  }

  public InlineResponseDefault8 addRecordsItem(PersonalContactInfo recordsItem) {
    this.records.add(recordsItem);
    return this;
  }

   /**
   * List of contacts with synchronization information
   * @return records
  **/
  @ApiModelProperty(example = "null", value = "List of contacts with synchronization information")
  public List<PersonalContactInfo> getRecords() {
    return records;
  }

  public void setRecords(List<PersonalContactInfo> records) {
    this.records = records;
  }

  public InlineResponseDefault8 syncInfo(SyncInfo syncInfo) {
    this.syncInfo = syncInfo;
    return this;
  }

   /**
   * Sync type, token and time
   * @return syncInfo
  **/
  @ApiModelProperty(example = "null", value = "Sync type, token and time")
  public SyncInfo getSyncInfo() {
    return syncInfo;
  }

  public void setSyncInfo(SyncInfo syncInfo) {
    this.syncInfo = syncInfo;
  }

  public InlineResponseDefault8 nextPageId(Integer nextPageId) {
    this.nextPageId = nextPageId;
    return this;
  }

   /**
   * Internal identifier of the next page, if any
   * @return nextPageId
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of the next page, if any")
  public Integer getNextPageId() {
    return nextPageId;
  }

  public void setNextPageId(Integer nextPageId) {
    this.nextPageId = nextPageId;
  }

  public InlineResponseDefault8 nextPageUri(String nextPageUri) {
    this.nextPageUri = nextPageUri;
    return this;
  }

   /**
   * URL of the next page, if any
   * @return nextPageUri
  **/
  @ApiModelProperty(example = "null", value = "URL of the next page, if any")
  public String getNextPageUri() {
    return nextPageUri;
  }

  public void setNextPageUri(String nextPageUri) {
    this.nextPageUri = nextPageUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponseDefault8 inlineResponseDefault8 = (InlineResponseDefault8) o;
    return Objects.equals(this.records, inlineResponseDefault8.records) &&
        Objects.equals(this.syncInfo, inlineResponseDefault8.syncInfo) &&
        Objects.equals(this.nextPageId, inlineResponseDefault8.nextPageId) &&
        Objects.equals(this.nextPageUri, inlineResponseDefault8.nextPageUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records, syncInfo, nextPageId, nextPageUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponseDefault8 {\n");
    
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    syncInfo: ").append(toIndentedString(syncInfo)).append("\n");
    sb.append("    nextPageId: ").append(toIndentedString(nextPageId)).append("\n");
    sb.append("    nextPageUri: ").append(toIndentedString(nextPageUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

