/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MessageInfo;
import io.swagger.client.model.SyncInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponseDefault22
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class InlineResponseDefault22 {
  @SerializedName("records")
  private List<MessageInfo> records = new ArrayList<MessageInfo>();

  @SerializedName("syncInfo")
  private SyncInfo syncInfo = null;

  public InlineResponseDefault22 records(List<MessageInfo> records) {
    this.records = records;
    return this;
  }

  public InlineResponseDefault22 addRecordsItem(MessageInfo recordsItem) {
    this.records.add(recordsItem);
    return this;
  }

   /**
   * List of message records with synchronization information
   * @return records
  **/
  @ApiModelProperty(example = "null", value = "List of message records with synchronization information")
  public List<MessageInfo> getRecords() {
    return records;
  }

  public void setRecords(List<MessageInfo> records) {
    this.records = records;
  }

  public InlineResponseDefault22 syncInfo(SyncInfo syncInfo) {
    this.syncInfo = syncInfo;
    return this;
  }

   /**
   * Sync type, token and time
   * @return syncInfo
  **/
  @ApiModelProperty(example = "null", value = "Sync type, token and time")
  public SyncInfo getSyncInfo() {
    return syncInfo;
  }

  public void setSyncInfo(SyncInfo syncInfo) {
    this.syncInfo = syncInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponseDefault22 inlineResponseDefault22 = (InlineResponseDefault22) o;
    return Objects.equals(this.records, inlineResponseDefault22.records) &&
        Objects.equals(this.syncInfo, inlineResponseDefault22.syncInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records, syncInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponseDefault22 {\n");
    
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    syncInfo: ").append(toIndentedString(syncInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

