/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PermissionDetailsInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponseDefault12
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class InlineResponseDefault12 {
  @SerializedName("uri")
  private String uri = null;

  @SerializedName("successful")
  private Boolean successful = null;

  @SerializedName("details")
  private PermissionDetailsInfo details = null;

  @SerializedName("scopes")
  private List<String> scopes = new ArrayList<String>();

  public InlineResponseDefault12 uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Canonical URI of a permission resource
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Canonical URI of a permission resource")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public InlineResponseDefault12 successful(Boolean successful) {
    this.successful = successful;
    return this;
  }

   /**
   * Specifies if check result is successful or not
   * @return successful
  **/
  @ApiModelProperty(example = "null", value = "Specifies if check result is successful or not")
  public Boolean getSuccessful() {
    return successful;
  }

  public void setSuccessful(Boolean successful) {
    this.successful = successful;
  }

  public InlineResponseDefault12 details(PermissionDetailsInfo details) {
    this.details = details;
    return this;
  }

   /**
   * Information on a permission checked. Returned if successful is 'True'
   * @return details
  **/
  @ApiModelProperty(example = "null", value = "Information on a permission checked. Returned if successful is 'True'")
  public PermissionDetailsInfo getDetails() {
    return details;
  }

  public void setDetails(PermissionDetailsInfo details) {
    this.details = details;
  }

  public InlineResponseDefault12 scopes(List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public InlineResponseDefault12 addScopesItem(String scopesItem) {
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * List of active scopes for permission. Returned if successful is 'True'
   * @return scopes
  **/
  @ApiModelProperty(example = "null", value = "List of active scopes for permission. Returned if successful is 'True'")
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(List<String> scopes) {
    this.scopes = scopes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponseDefault12 inlineResponseDefault12 = (InlineResponseDefault12) o;
    return Objects.equals(this.uri, inlineResponseDefault12.uri) &&
        Objects.equals(this.successful, inlineResponseDefault12.successful) &&
        Objects.equals(this.details, inlineResponseDefault12.details) &&
        Objects.equals(this.scopes, inlineResponseDefault12.scopes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, successful, details, scopes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponseDefault12 {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

