/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LookUpPhoneNumberPhoneNumberInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponseDefault36
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class InlineResponseDefault36 {
  @SerializedName("uri")
  private String uri = null;

  @SerializedName("records")
  private List<LookUpPhoneNumberPhoneNumberInfo> records = new ArrayList<LookUpPhoneNumberPhoneNumberInfo>();

  public InlineResponseDefault36 uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Canonical URI of the phone numbers resource
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Canonical URI of the phone numbers resource")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public InlineResponseDefault36 records(List<LookUpPhoneNumberPhoneNumberInfo> records) {
    this.records = records;
    return this;
  }

  public InlineResponseDefault36 addRecordsItem(LookUpPhoneNumberPhoneNumberInfo recordsItem) {
    this.records.add(recordsItem);
    return this;
  }

   /**
   * List of phone numbers filtered by the specified criteria
   * @return records
  **/
  @ApiModelProperty(example = "null", value = "List of phone numbers filtered by the specified criteria")
  public List<LookUpPhoneNumberPhoneNumberInfo> getRecords() {
    return records;
  }

  public void setRecords(List<LookUpPhoneNumberPhoneNumberInfo> records) {
    this.records = records;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponseDefault36 inlineResponseDefault36 = (InlineResponseDefault36) o;
    return Objects.equals(this.uri, inlineResponseDefault36.uri) &&
        Objects.equals(this.records, inlineResponseDefault36.records);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, records);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponseDefault36 {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

