/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LanguageInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class LanguageInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("greeting")
  private Boolean greeting = null;

  @SerializedName("formattingLocale")
  private Boolean formattingLocale = null;

  @SerializedName("localeCode")
  private String localeCode = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("ui")
  private Boolean ui = null;

  public LanguageInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of a language
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a language")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public LanguageInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Canonical URI of a language
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Canonical URI of a language")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public LanguageInfo greeting(Boolean greeting) {
    this.greeting = greeting;
    return this;
  }

   /**
   * Indicates whether a language is available as greeting language
   * @return greeting
  **/
  @ApiModelProperty(example = "null", value = "Indicates whether a language is available as greeting language")
  public Boolean getGreeting() {
    return greeting;
  }

  public void setGreeting(Boolean greeting) {
    this.greeting = greeting;
  }

  public LanguageInfo formattingLocale(Boolean formattingLocale) {
    this.formattingLocale = formattingLocale;
    return this;
  }

   /**
   * Indicates whether a language is available as formatting locale
   * @return formattingLocale
  **/
  @ApiModelProperty(example = "null", value = "Indicates whether a language is available as formatting locale")
  public Boolean getFormattingLocale() {
    return formattingLocale;
  }

  public void setFormattingLocale(Boolean formattingLocale) {
    this.formattingLocale = formattingLocale;
  }

  public LanguageInfo localeCode(String localeCode) {
    this.localeCode = localeCode;
    return this;
  }

   /**
   * Localization code of a language
   * @return localeCode
  **/
  @ApiModelProperty(example = "null", value = "Localization code of a language")
  public String getLocaleCode() {
    return localeCode;
  }

  public void setLocaleCode(String localeCode) {
    this.localeCode = localeCode;
  }

  public LanguageInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Official name of a language
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Official name of a language")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LanguageInfo ui(Boolean ui) {
    this.ui = ui;
    return this;
  }

   /**
   * Indicates whether a language is available as UI language
   * @return ui
  **/
  @ApiModelProperty(example = "null", value = "Indicates whether a language is available as UI language")
  public Boolean getUi() {
    return ui;
  }

  public void setUi(Boolean ui) {
    this.ui = ui;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LanguageInfo languageInfo = (LanguageInfo) o;
    return Objects.equals(this.id, languageInfo.id) &&
        Objects.equals(this.uri, languageInfo.uri) &&
        Objects.equals(this.greeting, languageInfo.greeting) &&
        Objects.equals(this.formattingLocale, languageInfo.formattingLocale) &&
        Objects.equals(this.localeCode, languageInfo.localeCode) &&
        Objects.equals(this.name, languageInfo.name) &&
        Objects.equals(this.ui, languageInfo.ui);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri, greeting, formattingLocale, localeCode, name, ui);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LanguageInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    greeting: ").append(toIndentedString(greeting)).append("\n");
    sb.append("    formattingLocale: ").append(toIndentedString(formattingLocale)).append("\n");
    sb.append("    localeCode: ").append(toIndentedString(localeCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ui: ").append(toIndentedString(ui)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

