/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CallerInfo;
import io.swagger.client.model.LegInfoExtensionInfo;
import io.swagger.client.model.RecordingInfo;
import org.joda.time.DateTime;

/**
 * LegInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class LegInfo {
  /**
   * Action description of the call operation
   */
  public enum ActionEnum {
    @SerializedName("Unknown")
    UNKNOWN("Unknown"),
    
    @SerializedName("Phone Call")
    PHONE_CALL("Phone Call"),
    
    @SerializedName("Phone Login")
    PHONE_LOGIN("Phone Login"),
    
    @SerializedName("Incoming Fax")
    INCOMING_FAX("Incoming Fax"),
    
    @SerializedName("Accept Call")
    ACCEPT_CALL("Accept Call"),
    
    @SerializedName("FindMe")
    FINDME("FindMe"),
    
    @SerializedName("FollowMe")
    FOLLOWME("FollowMe"),
    
    @SerializedName("Outgoing Fax")
    OUTGOING_FAX("Outgoing Fax"),
    
    @SerializedName("Call Return")
    CALL_RETURN("Call Return"),
    
    @SerializedName("Calling Card")
    CALLING_CARD("Calling Card"),
    
    @SerializedName("Ring Directly")
    RING_DIRECTLY("Ring Directly"),
    
    @SerializedName("RingOut Web")
    RINGOUT_WEB("RingOut Web"),
    
    @SerializedName("VoIP Call")
    VOIP_CALL("VoIP Call"),
    
    @SerializedName("RingOut PC")
    RINGOUT_PC("RingOut PC"),
    
    @SerializedName("RingMe")
    RINGME("RingMe"),
    
    @SerializedName("Transfer")
    TRANSFER("Transfer"),
    
    @SerializedName("411 Info")
    _411_INFO("411 Info"),
    
    @SerializedName("Emergency")
    EMERGENCY("Emergency"),
    
    @SerializedName("E911 Update")
    E911_UPDATE("E911 Update"),
    
    @SerializedName("Support")
    SUPPORT("Support"),
    
    @SerializedName("RingOut Mobile")
    RINGOUT_MOBILE("RingOut Mobile");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("action")
  private ActionEnum action = null;

  /**
   * Call direction
   */
  public enum DirectionEnum {
    @SerializedName("Inbound")
    INBOUND("Inbound"),
    
    @SerializedName("Outbound")
    OUTBOUND("Outbound");

    private String value;

    DirectionEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("direction")
  private DirectionEnum direction = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("extension")
  private LegInfoExtensionInfo extension = null;

  @SerializedName("legType")
  private String legType = null;

  @SerializedName("startTime")
  private DateTime startTime = null;

  /**
   * Call type
   */
  public enum TypeEnum {
    @SerializedName("Voice")
    VOICE("Voice"),
    
    @SerializedName("Fax")
    FAX("Fax");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  /**
   * Status description of the call operation
   */
  public enum ResultEnum {
    @SerializedName("Unknown")
    UNKNOWN("Unknown"),
    
    @SerializedName("ResultInProgress")
    RESULTINPROGRESS("ResultInProgress"),
    
    @SerializedName("Missed")
    MISSED("Missed"),
    
    @SerializedName("Call accepted")
    CALL_ACCEPTED("Call accepted"),
    
    @SerializedName("Voicemail")
    VOICEMAIL("Voicemail"),
    
    @SerializedName("Rejected")
    REJECTED("Rejected"),
    
    @SerializedName("Reply")
    REPLY("Reply"),
    
    @SerializedName("Received")
    RECEIVED("Received"),
    
    @SerializedName("Receive Error")
    RECEIVE_ERROR("Receive Error"),
    
    @SerializedName("Fax on Demand")
    FAX_ON_DEMAND("Fax on Demand"),
    
    @SerializedName("Partial Receive")
    PARTIAL_RECEIVE("Partial Receive"),
    
    @SerializedName("Blocked")
    BLOCKED("Blocked"),
    
    @SerializedName("Call connected")
    CALL_CONNECTED("Call connected"),
    
    @SerializedName("No Answer")
    NO_ANSWER("No Answer"),
    
    @SerializedName("International Disabled")
    INTERNATIONAL_DISABLED("International Disabled"),
    
    @SerializedName("Busy")
    BUSY("Busy"),
    
    @SerializedName("Send Error")
    SEND_ERROR("Send Error"),
    
    @SerializedName("Sent")
    SENT("Sent"),
    
    @SerializedName("No fax machine")
    NO_FAX_MACHINE("No fax machine"),
    
    @SerializedName("ResultEmpty")
    RESULTEMPTY("ResultEmpty"),
    
    @SerializedName("Account")
    ACCOUNT("Account"),
    
    @SerializedName("Suspended")
    SUSPENDED("Suspended"),
    
    @SerializedName("Call Failed")
    CALL_FAILED("Call Failed"),
    
    @SerializedName("Call Failure")
    CALL_FAILURE("Call Failure"),
    
    @SerializedName("Internal Error")
    INTERNAL_ERROR("Internal Error"),
    
    @SerializedName("IP Phone offline")
    IP_PHONE_OFFLINE("IP Phone offline"),
    
    @SerializedName("Restricted Number")
    RESTRICTED_NUMBER("Restricted Number"),
    
    @SerializedName("Wrong Number")
    WRONG_NUMBER("Wrong Number"),
    
    @SerializedName("Stopped")
    STOPPED("Stopped"),
    
    @SerializedName("Hang up")
    HANG_UP("Hang up"),
    
    @SerializedName("Poor Line Quality")
    POOR_LINE_QUALITY("Poor Line Quality"),
    
    @SerializedName("Partially Sent")
    PARTIALLY_SENT("Partially Sent"),
    
    @SerializedName("International Restriction")
    INTERNATIONAL_RESTRICTION("International Restriction"),
    
    @SerializedName("Abandoned")
    ABANDONED("Abandoned"),
    
    @SerializedName("Declined")
    DECLINED("Declined"),
    
    @SerializedName("Fax Receipt Error")
    FAX_RECEIPT_ERROR("Fax Receipt Error"),
    
    @SerializedName("Fax Send Error")
    FAX_SEND_ERROR("Fax Send Error");

    private String value;

    ResultEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("result")
  private ResultEnum result = null;

  @SerializedName("from")
  private CallerInfo from = null;

  @SerializedName("to")
  private CallerInfo to = null;

  /**
   * Call transport
   */
  public enum TransportEnum {
    @SerializedName("PSTN")
    PSTN("PSTN"),
    
    @SerializedName("VoIP")
    VOIP("VoIP");

    private String value;

    TransportEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("transport")
  private TransportEnum transport = null;

  @SerializedName("recording")
  private RecordingInfo recording = null;

  public LegInfo action(ActionEnum action) {
    this.action = action;
    return this;
  }

   /**
   * Action description of the call operation
   * @return action
  **/
  @ApiModelProperty(example = "null", value = "Action description of the call operation")
  public ActionEnum getAction() {
    return action;
  }

  public void setAction(ActionEnum action) {
    this.action = action;
  }

  public LegInfo direction(DirectionEnum direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Call direction
   * @return direction
  **/
  @ApiModelProperty(example = "null", value = "Call direction")
  public DirectionEnum getDirection() {
    return direction;
  }

  public void setDirection(DirectionEnum direction) {
    this.direction = direction;
  }

  public LegInfo duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Call duration in seconds
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "Call duration in seconds")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public LegInfo extension(LegInfoExtensionInfo extension) {
    this.extension = extension;
    return this;
  }

   /**
   * Information on extension
   * @return extension
  **/
  @ApiModelProperty(example = "null", value = "Information on extension")
  public LegInfoExtensionInfo getExtension() {
    return extension;
  }

  public void setExtension(LegInfoExtensionInfo extension) {
    this.extension = extension;
  }

  public LegInfo legType(String legType) {
    this.legType = legType;
    return this;
  }

   /**
   * Leg type
   * @return legType
  **/
  @ApiModelProperty(example = "null", value = "Leg type")
  public String getLegType() {
    return legType;
  }

  public void setLegType(String legType) {
    this.legType = legType;
  }

  public LegInfo startTime(DateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * The call start datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
   * @return startTime
  **/
  @ApiModelProperty(example = "null", value = "The call start datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z")
  public DateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(DateTime startTime) {
    this.startTime = startTime;
  }

  public LegInfo type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Call type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "Call type")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public LegInfo result(ResultEnum result) {
    this.result = result;
    return this;
  }

   /**
   * Status description of the call operation
   * @return result
  **/
  @ApiModelProperty(example = "null", value = "Status description of the call operation")
  public ResultEnum getResult() {
    return result;
  }

  public void setResult(ResultEnum result) {
    this.result = result;
  }

  public LegInfo from(CallerInfo from) {
    this.from = from;
    return this;
  }

   /**
   * Caller information
   * @return from
  **/
  @ApiModelProperty(example = "null", value = "Caller information")
  public CallerInfo getFrom() {
    return from;
  }

  public void setFrom(CallerInfo from) {
    this.from = from;
  }

  public LegInfo to(CallerInfo to) {
    this.to = to;
    return this;
  }

   /**
   * Callee information
   * @return to
  **/
  @ApiModelProperty(example = "null", value = "Callee information")
  public CallerInfo getTo() {
    return to;
  }

  public void setTo(CallerInfo to) {
    this.to = to;
  }

  public LegInfo transport(TransportEnum transport) {
    this.transport = transport;
    return this;
  }

   /**
   * Call transport
   * @return transport
  **/
  @ApiModelProperty(example = "null", value = "Call transport")
  public TransportEnum getTransport() {
    return transport;
  }

  public void setTransport(TransportEnum transport) {
    this.transport = transport;
  }

  public LegInfo recording(RecordingInfo recording) {
    this.recording = recording;
    return this;
  }

   /**
   * Call recording data. Returned if the call is recorded
   * @return recording
  **/
  @ApiModelProperty(example = "null", value = "Call recording data. Returned if the call is recorded")
  public RecordingInfo getRecording() {
    return recording;
  }

  public void setRecording(RecordingInfo recording) {
    this.recording = recording;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegInfo legInfo = (LegInfo) o;
    return Objects.equals(this.action, legInfo.action) &&
        Objects.equals(this.direction, legInfo.direction) &&
        Objects.equals(this.duration, legInfo.duration) &&
        Objects.equals(this.extension, legInfo.extension) &&
        Objects.equals(this.legType, legInfo.legType) &&
        Objects.equals(this.startTime, legInfo.startTime) &&
        Objects.equals(this.type, legInfo.type) &&
        Objects.equals(this.result, legInfo.result) &&
        Objects.equals(this.from, legInfo.from) &&
        Objects.equals(this.to, legInfo.to) &&
        Objects.equals(this.transport, legInfo.transport) &&
        Objects.equals(this.recording, legInfo.recording);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, direction, duration, extension, legType, startTime, type, result, from, to, transport, recording);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegInfo {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    legType: ").append(toIndentedString(legType)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    transport: ").append(toIndentedString(transport)).append("\n");
    sb.append("    recording: ").append(toIndentedString(recording)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

