/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MeetingScheduleInfoTimezoneInfo;
import org.joda.time.DateTime;

/**
 * MeetingScheduleInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class MeetingScheduleInfo {
  @SerializedName("startTime")
  private DateTime startTime = null;

  @SerializedName("durationInMinutes")
  private Integer durationInMinutes = null;

  @SerializedName("timeZone")
  private MeetingScheduleInfoTimezoneInfo timeZone = null;

  public MeetingScheduleInfo startTime(DateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Start time of a meeting in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
   * @return startTime
  **/
  @ApiModelProperty(example = "null", value = "Start time of a meeting in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z")
  public DateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(DateTime startTime) {
    this.startTime = startTime;
  }

  public MeetingScheduleInfo durationInMinutes(Integer durationInMinutes) {
    this.durationInMinutes = durationInMinutes;
    return this;
  }

   /**
   * Duration of a meeting in minutes
   * @return durationInMinutes
  **/
  @ApiModelProperty(example = "null", value = "Duration of a meeting in minutes")
  public Integer getDurationInMinutes() {
    return durationInMinutes;
  }

  public void setDurationInMinutes(Integer durationInMinutes) {
    this.durationInMinutes = durationInMinutes;
  }

  public MeetingScheduleInfo timeZone(MeetingScheduleInfoTimezoneInfo timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Timezone of a meeting
   * @return timeZone
  **/
  @ApiModelProperty(example = "null", value = "Timezone of a meeting")
  public MeetingScheduleInfoTimezoneInfo getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(MeetingScheduleInfoTimezoneInfo timeZone) {
    this.timeZone = timeZone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeetingScheduleInfo meetingScheduleInfo = (MeetingScheduleInfo) o;
    return Objects.equals(this.startTime, meetingScheduleInfo.startTime) &&
        Objects.equals(this.durationInMinutes, meetingScheduleInfo.durationInMinutes) &&
        Objects.equals(this.timeZone, meetingScheduleInfo.timeZone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startTime, durationInMinutes, timeZone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeetingScheduleInfo {\n");
    
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    durationInMinutes: ").append(toIndentedString(durationInMinutes)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

