/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AddonInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * ModelInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class ModelInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("addons")
  private List<AddonInfo> addons = new ArrayList<AddonInfo>();

  public ModelInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Device model identifier. Mandatory when ordering a HardPhone if boxBillingId is not used for ordering
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Device model identifier. Mandatory when ordering a HardPhone if boxBillingId is not used for ordering")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ModelInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Device name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Device name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ModelInfo addons(List<AddonInfo> addons) {
    this.addons = addons;
    return this;
  }

  public ModelInfo addAddonsItem(AddonInfo addonsItem) {
    this.addons.add(addonsItem);
    return this;
  }

   /**
   * Addons description
   * @return addons
  **/
  @ApiModelProperty(example = "null", value = "Addons description")
  public List<AddonInfo> getAddons() {
    return addons;
  }

  public void setAddons(List<AddonInfo> addons) {
    this.addons = addons;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelInfo modelInfo = (ModelInfo) o;
    return Objects.equals(this.id, modelInfo.id) &&
        Objects.equals(this.name, modelInfo.name) &&
        Objects.equals(this.addons, modelInfo.addons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, addons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    addons: ").append(toIndentedString(addons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

