/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Page;

/**
 * NavigationInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class NavigationInfo {
  @SerializedName("firstPage")
  private Page firstPage = null;

  @SerializedName("nextPage")
  private Page nextPage = null;

  @SerializedName("previousPage")
  private Page previousPage = null;

  @SerializedName("lastPage")
  private Page lastPage = null;

  public NavigationInfo firstPage(Page firstPage) {
    this.firstPage = firstPage;
    return this;
  }

   /**
   * First page of the list
   * @return firstPage
  **/
  @ApiModelProperty(example = "null", value = "First page of the list")
  public Page getFirstPage() {
    return firstPage;
  }

  public void setFirstPage(Page firstPage) {
    this.firstPage = firstPage;
  }

  public NavigationInfo nextPage(Page nextPage) {
    this.nextPage = nextPage;
    return this;
  }

   /**
   * Next page of the list
   * @return nextPage
  **/
  @ApiModelProperty(example = "null", value = "Next page of the list")
  public Page getNextPage() {
    return nextPage;
  }

  public void setNextPage(Page nextPage) {
    this.nextPage = nextPage;
  }

  public NavigationInfo previousPage(Page previousPage) {
    this.previousPage = previousPage;
    return this;
  }

   /**
   * Previous page of the list
   * @return previousPage
  **/
  @ApiModelProperty(example = "null", value = "Previous page of the list")
  public Page getPreviousPage() {
    return previousPage;
  }

  public void setPreviousPage(Page previousPage) {
    this.previousPage = previousPage;
  }

  public NavigationInfo lastPage(Page lastPage) {
    this.lastPage = lastPage;
    return this;
  }

   /**
   * Last page of the list
   * @return lastPage
  **/
  @ApiModelProperty(example = "null", value = "Last page of the list")
  public Page getLastPage() {
    return lastPage;
  }

  public void setLastPage(Page lastPage) {
    this.lastPage = lastPage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NavigationInfo navigationInfo = (NavigationInfo) o;
    return Objects.equals(this.firstPage, navigationInfo.firstPage) &&
        Objects.equals(this.nextPage, navigationInfo.nextPage) &&
        Objects.equals(this.previousPage, navigationInfo.previousPage) &&
        Objects.equals(this.lastPage, navigationInfo.lastPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstPage, nextPage, previousPage, lastPage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NavigationInfo {\n");
    
    sb.append("    firstPage: ").append(toIndentedString(firstPage)).append("\n");
    sb.append("    nextPage: ").append(toIndentedString(nextPage)).append("\n");
    sb.append("    previousPage: ").append(toIndentedString(previousPage)).append("\n");
    sb.append("    lastPage: ").append(toIndentedString(lastPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

