/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserPermissionInfo;

/**
 * PermissionDetailsInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class PermissionDetailsInfo {
  @SerializedName("permission")
  private UserPermissionInfo permission = null;

  public PermissionDetailsInfo permission(UserPermissionInfo permission) {
    this.permission = permission;
    return this;
  }

   /**
   * Information on a permission checked
   * @return permission
  **/
  @ApiModelProperty(example = "null", value = "Information on a permission checked")
  public UserPermissionInfo getPermission() {
    return permission;
  }

  public void setPermission(UserPermissionInfo permission) {
    this.permission = permission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionDetailsInfo permissionDetailsInfo = (PermissionDetailsInfo) o;
    return Objects.equals(this.permission, permissionDetailsInfo.permission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionDetailsInfo {\n");
    
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

