/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ImageUri;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * ProfileImageInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class ProfileImageInfo {
  @SerializedName("uri")
  private String uri = null;

  @SerializedName("etag")
  private String etag = null;

  @SerializedName("lastModified")
  private DateTime lastModified = null;

  @SerializedName("contentType")
  private String contentType = null;

  @SerializedName("scales")
  private List<ImageUri> scales = new ArrayList<ImageUri>();

  public ProfileImageInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Link to a profile image. If an image is not uploaded for an extension, only uri is returned
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Link to a profile image. If an image is not uploaded for an extension, only uri is returned")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public ProfileImageInfo etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * Identifier of an image
   * @return etag
  **/
  @ApiModelProperty(example = "null", value = "Identifier of an image")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }

  public ProfileImageInfo lastModified(DateTime lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * The datetime when an image was last updated in ISO 8601 format, for example 2016-03-10T18:07:52.534Z
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "The datetime when an image was last updated in ISO 8601 format, for example 2016-03-10T18:07:52.534Z")
  public DateTime getLastModified() {
    return lastModified;
  }

  public void setLastModified(DateTime lastModified) {
    this.lastModified = lastModified;
  }

  public ProfileImageInfo contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * The type of an image
   * @return contentType
  **/
  @ApiModelProperty(example = "null", value = "The type of an image")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public ProfileImageInfo scales(List<ImageUri> scales) {
    this.scales = scales;
    return this;
  }

  public ProfileImageInfo addScalesItem(ImageUri scalesItem) {
    this.scales.add(scalesItem);
    return this;
  }

   /**
   * List of URIs to profile images in different dimensions
   * @return scales
  **/
  @ApiModelProperty(example = "null", value = "List of URIs to profile images in different dimensions")
  public List<ImageUri> getScales() {
    return scales;
  }

  public void setScales(List<ImageUri> scales) {
    this.scales = scales;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileImageInfo profileImageInfo = (ProfileImageInfo) o;
    return Objects.equals(this.uri, profileImageInfo.uri) &&
        Objects.equals(this.etag, profileImageInfo.etag) &&
        Objects.equals(this.lastModified, profileImageInfo.lastModified) &&
        Objects.equals(this.contentType, profileImageInfo.contentType) &&
        Objects.equals(this.scales, profileImageInfo.scales);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, etag, lastModified, contentType, scales);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileImageInfo {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    scales: ").append(toIndentedString(scales)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

