/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RecordingInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class RecordingInfo {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("uri")
  private String uri = null;

  /**
   * Indicates recording mode used
   */
  public enum TypeEnum {
    @SerializedName("Automatic")
    AUTOMATIC("Automatic"),
    
    @SerializedName("OnDemand")
    ONDEMAND("OnDemand");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("contentUri")
  private String contentUri = null;

  public RecordingInfo id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of the call recording
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of the call recording")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public RecordingInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Link to the call recording metadata resource
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Link to the call recording metadata resource")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public RecordingInfo type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Indicates recording mode used
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "Indicates recording mode used")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public RecordingInfo contentUri(String contentUri) {
    this.contentUri = contentUri;
    return this;
  }

   /**
   * Link to the call recording binary content
   * @return contentUri
  **/
  @ApiModelProperty(example = "null", value = "Link to the call recording binary content")
  public String getContentUri() {
    return contentUri;
  }

  public void setContentUri(String contentUri) {
    this.contentUri = contentUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecordingInfo recordingInfo = (RecordingInfo) o;
    return Objects.equals(this.id, recordingInfo.id) &&
        Objects.equals(this.uri, recordingInfo.uri) &&
        Objects.equals(this.type, recordingInfo.type) &&
        Objects.equals(this.contentUri, recordingInfo.contentUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri, type, contentUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecordingInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    contentUri: ").append(toIndentedString(contentUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

