/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RingOutStatusInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class RingOutStatusInfo {
  /**
   * Status of a call
   */
  public enum CallStatusEnum {
    @SerializedName("Invalid")
    INVALID("Invalid"),
    
    @SerializedName("Success")
    SUCCESS("Success"),
    
    @SerializedName("InProgress")
    INPROGRESS("InProgress"),
    
    @SerializedName("Busy")
    BUSY("Busy"),
    
    @SerializedName("NoAnswer")
    NOANSWER("NoAnswer"),
    
    @SerializedName("Rejected")
    REJECTED("Rejected"),
    
    @SerializedName("GenericError")
    GENERICERROR("GenericError"),
    
    @SerializedName("Finished")
    FINISHED("Finished"),
    
    @SerializedName("InternationalDisabled")
    INTERNATIONALDISABLED("InternationalDisabled"),
    
    @SerializedName("DestinationBlocked")
    DESTINATIONBLOCKED("DestinationBlocked"),
    
    @SerializedName("NotEnoughFunds")
    NOTENOUGHFUNDS("NotEnoughFunds"),
    
    @SerializedName("NoSuchUser")
    NOSUCHUSER("NoSuchUser");

    private String value;

    CallStatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("callStatus")
  private CallStatusEnum callStatus = null;

  /**
   * Status of a calling party
   */
  public enum CallerStatusEnum {
    @SerializedName("Invalid")
    INVALID("Invalid"),
    
    @SerializedName("Success")
    SUCCESS("Success"),
    
    @SerializedName("InProgress")
    INPROGRESS("InProgress"),
    
    @SerializedName("Busy")
    BUSY("Busy"),
    
    @SerializedName("NoAnswer")
    NOANSWER("NoAnswer"),
    
    @SerializedName("Rejected")
    REJECTED("Rejected"),
    
    @SerializedName("GenericError")
    GENERICERROR("GenericError"),
    
    @SerializedName("Finished")
    FINISHED("Finished"),
    
    @SerializedName("InternationalDisabled")
    INTERNATIONALDISABLED("InternationalDisabled"),
    
    @SerializedName("DestinationBlocked")
    DESTINATIONBLOCKED("DestinationBlocked"),
    
    @SerializedName("NotEnoughFunds")
    NOTENOUGHFUNDS("NotEnoughFunds"),
    
    @SerializedName("NoSuchUser")
    NOSUCHUSER("NoSuchUser");

    private String value;

    CallerStatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("callerStatus")
  private CallerStatusEnum callerStatus = null;

  /**
   * Status of a called party
   */
  public enum CalleeStatusEnum {
    @SerializedName("Invalid")
    INVALID("Invalid"),
    
    @SerializedName("Success")
    SUCCESS("Success"),
    
    @SerializedName("InProgress")
    INPROGRESS("InProgress"),
    
    @SerializedName("Busy")
    BUSY("Busy"),
    
    @SerializedName("NoAnswer")
    NOANSWER("NoAnswer"),
    
    @SerializedName("Rejected")
    REJECTED("Rejected"),
    
    @SerializedName("GenericError")
    GENERICERROR("GenericError"),
    
    @SerializedName("Finished")
    FINISHED("Finished"),
    
    @SerializedName("InternationalDisabled")
    INTERNATIONALDISABLED("InternationalDisabled"),
    
    @SerializedName("DestinationBlocked")
    DESTINATIONBLOCKED("DestinationBlocked"),
    
    @SerializedName("NotEnoughFunds")
    NOTENOUGHFUNDS("NotEnoughFunds"),
    
    @SerializedName("NoSuchUser")
    NOSUCHUSER("NoSuchUser");

    private String value;

    CalleeStatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("calleeStatus")
  private CalleeStatusEnum calleeStatus = null;

  public RingOutStatusInfo callStatus(CallStatusEnum callStatus) {
    this.callStatus = callStatus;
    return this;
  }

   /**
   * Status of a call
   * @return callStatus
  **/
  @ApiModelProperty(example = "null", value = "Status of a call")
  public CallStatusEnum getCallStatus() {
    return callStatus;
  }

  public void setCallStatus(CallStatusEnum callStatus) {
    this.callStatus = callStatus;
  }

  public RingOutStatusInfo callerStatus(CallerStatusEnum callerStatus) {
    this.callerStatus = callerStatus;
    return this;
  }

   /**
   * Status of a calling party
   * @return callerStatus
  **/
  @ApiModelProperty(example = "null", value = "Status of a calling party")
  public CallerStatusEnum getCallerStatus() {
    return callerStatus;
  }

  public void setCallerStatus(CallerStatusEnum callerStatus) {
    this.callerStatus = callerStatus;
  }

  public RingOutStatusInfo calleeStatus(CalleeStatusEnum calleeStatus) {
    this.calleeStatus = calleeStatus;
    return this;
  }

   /**
   * Status of a called party
   * @return calleeStatus
  **/
  @ApiModelProperty(example = "null", value = "Status of a called party")
  public CalleeStatusEnum getCalleeStatus() {
    return calleeStatus;
  }

  public void setCalleeStatus(CalleeStatusEnum calleeStatus) {
    this.calleeStatus = calleeStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RingOutStatusInfo ringOutStatusInfo = (RingOutStatusInfo) o;
    return Objects.equals(this.callStatus, ringOutStatusInfo.callStatus) &&
        Objects.equals(this.callerStatus, ringOutStatusInfo.callerStatus) &&
        Objects.equals(this.calleeStatus, ringOutStatusInfo.calleeStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callStatus, callerStatus, calleeStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RingOutStatusInfo {\n");
    
    sb.append("    callStatus: ").append(toIndentedString(callStatus)).append("\n");
    sb.append("    callerStatus: ").append(toIndentedString(callerStatus)).append("\n");
    sb.append("    calleeStatus: ").append(toIndentedString(calleeStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

