/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RingOutRequestFrom
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class RingOutRequestFrom {
  @SerializedName("phoneNumber")
  private String phoneNumber = null;

  @SerializedName("forwardingNumberId")
  private String forwardingNumberId = null;

  public RingOutRequestFrom phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Phone number in E.164 format
   * @return phoneNumber
  **/
  @ApiModelProperty(example = "null", value = "Phone number in E.164 format")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public RingOutRequestFrom forwardingNumberId(String forwardingNumberId) {
    this.forwardingNumberId = forwardingNumberId;
    return this;
  }

   /**
   * Internal identifier of a forwarding number; returned in response in the id field. Can be specified instead of the phoneNumber attribute
   * @return forwardingNumberId
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a forwarding number; returned in response in the id field. Can be specified instead of the phoneNumber attribute")
  public String getForwardingNumberId() {
    return forwardingNumberId;
  }

  public void setForwardingNumberId(String forwardingNumberId) {
    this.forwardingNumberId = forwardingNumberId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RingOutRequestFrom ringOutRequestFrom = (RingOutRequestFrom) o;
    return Objects.equals(this.phoneNumber, ringOutRequestFrom.phoneNumber) &&
        Objects.equals(this.forwardingNumberId, ringOutRequestFrom.forwardingNumberId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneNumber, forwardingNumberId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RingOutRequestFrom {\n");
    
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    forwardingNumberId: ").append(toIndentedString(forwardingNumberId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

