/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RuleInfoForwardingNumberInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * RuleInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class RuleInfo {
  @SerializedName("index")
  private Integer index = null;

  @SerializedName("ringCount")
  private Integer ringCount = null;

  @SerializedName("forwardingNumbers")
  private List<RuleInfoForwardingNumberInfo> forwardingNumbers = new ArrayList<RuleInfoForwardingNumberInfo>();

  public RuleInfo index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Forwarding number (or group) ordinal
   * @return index
  **/
  @ApiModelProperty(example = "null", value = "Forwarding number (or group) ordinal")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public RuleInfo ringCount(Integer ringCount) {
    this.ringCount = ringCount;
    return this;
  }

   /**
   * Number of rings for a forwarding number (or group)
   * @return ringCount
  **/
  @ApiModelProperty(example = "null", value = "Number of rings for a forwarding number (or group)")
  public Integer getRingCount() {
    return ringCount;
  }

  public void setRingCount(Integer ringCount) {
    this.ringCount = ringCount;
  }

  public RuleInfo forwardingNumbers(List<RuleInfoForwardingNumberInfo> forwardingNumbers) {
    this.forwardingNumbers = forwardingNumbers;
    return this;
  }

  public RuleInfo addForwardingNumbersItem(RuleInfoForwardingNumberInfo forwardingNumbersItem) {
    this.forwardingNumbers.add(forwardingNumbersItem);
    return this;
  }

   /**
   * Forwarding number (or group) data
   * @return forwardingNumbers
  **/
  @ApiModelProperty(example = "null", value = "Forwarding number (or group) data")
  public List<RuleInfoForwardingNumberInfo> getForwardingNumbers() {
    return forwardingNumbers;
  }

  public void setForwardingNumbers(List<RuleInfoForwardingNumberInfo> forwardingNumbers) {
    this.forwardingNumbers = forwardingNumbers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleInfo ruleInfo = (RuleInfo) o;
    return Objects.equals(this.index, ruleInfo.index) &&
        Objects.equals(this.ringCount, ruleInfo.ringCount) &&
        Objects.equals(this.forwardingNumbers, ruleInfo.forwardingNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, ringCount, forwardingNumbers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleInfo {\n");
    
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    ringCount: ").append(toIndentedString(ringCount)).append("\n");
    sb.append("    forwardingNumbers: ").append(toIndentedString(forwardingNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

