/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RuleInfoForwardingNumberInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class RuleInfoForwardingNumberInfo {
  @SerializedName("uri")
  private String uri = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("phoneNumber")
  private String phoneNumber = null;

  @SerializedName("label")
  private String label = null;

  public RuleInfoForwardingNumberInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Link to a forwarding number resource
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Link to a forwarding number resource")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public RuleInfoForwardingNumberInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of a forwarding number
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a forwarding number")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RuleInfoForwardingNumberInfo phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Phone number to which the call is forwarded
   * @return phoneNumber
  **/
  @ApiModelProperty(example = "null", value = "Phone number to which the call is forwarded")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public RuleInfoForwardingNumberInfo label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Title of a forwarding number
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "Title of a forwarding number")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleInfoForwardingNumberInfo ruleInfoForwardingNumberInfo = (RuleInfoForwardingNumberInfo) o;
    return Objects.equals(this.uri, ruleInfoForwardingNumberInfo.uri) &&
        Objects.equals(this.id, ruleInfoForwardingNumberInfo.id) &&
        Objects.equals(this.phoneNumber, ruleInfoForwardingNumberInfo.phoneNumber) &&
        Objects.equals(this.label, ruleInfoForwardingNumberInfo.label);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, id, phoneNumber, label);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleInfoForwardingNumberInfo {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

