/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RangesInfo;
import io.swagger.client.model.WeeklyScheduleInfo;

/**
 * ScheduleInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class ScheduleInfo {
  @SerializedName("weeklyRanges")
  private WeeklyScheduleInfo weeklyRanges = null;

  @SerializedName("ranges")
  private RangesInfo ranges = null;

  /**
   * The user's schedule specified for business hours or after hours; it can also be set/retrieved calling the corresponding method
   */
  public enum RefEnum {
    @SerializedName("BusinessHours")
    BUSINESSHOURS("BusinessHours"),
    
    @SerializedName("AfterHours")
    AFTERHOURS("AfterHours");

    private String value;

    RefEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("ref")
  private RefEnum ref = null;

  public ScheduleInfo weeklyRanges(WeeklyScheduleInfo weeklyRanges) {
    this.weeklyRanges = weeklyRanges;
    return this;
  }

   /**
   * Weekly schedule
   * @return weeklyRanges
  **/
  @ApiModelProperty(example = "null", value = "Weekly schedule")
  public WeeklyScheduleInfo getWeeklyRanges() {
    return weeklyRanges;
  }

  public void setWeeklyRanges(WeeklyScheduleInfo weeklyRanges) {
    this.weeklyRanges = weeklyRanges;
  }

  public ScheduleInfo ranges(RangesInfo ranges) {
    this.ranges = ranges;
    return this;
  }

   /**
   * Specific data ranges
   * @return ranges
  **/
  @ApiModelProperty(example = "null", value = "Specific data ranges")
  public RangesInfo getRanges() {
    return ranges;
  }

  public void setRanges(RangesInfo ranges) {
    this.ranges = ranges;
  }

  public ScheduleInfo ref(RefEnum ref) {
    this.ref = ref;
    return this;
  }

   /**
   * The user's schedule specified for business hours or after hours; it can also be set/retrieved calling the corresponding method
   * @return ref
  **/
  @ApiModelProperty(example = "null", value = "The user's schedule specified for business hours or after hours; it can also be set/retrieved calling the corresponding method")
  public RefEnum getRef() {
    return ref;
  }

  public void setRef(RefEnum ref) {
    this.ref = ref;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleInfo scheduleInfo = (ScheduleInfo) o;
    return Objects.equals(this.weeklyRanges, scheduleInfo.weeklyRanges) &&
        Objects.equals(this.ranges, scheduleInfo.ranges) &&
        Objects.equals(this.ref, scheduleInfo.ref);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weeklyRanges, ranges, ref);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleInfo {\n");
    
    sb.append("    weeklyRanges: ").append(toIndentedString(weeklyRanges)).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

