/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ServicePlanInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class ServicePlanInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("edition")
  private String edition = null;

  public ServicePlanInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of a service plan
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a service plan")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ServicePlanInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of a service plan
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name of a service plan")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ServicePlanInfo edition(String edition) {
    this.edition = edition;
    return this;
  }

   /**
   * Edition of a service plan
   * @return edition
  **/
  @ApiModelProperty(example = "null", value = "Edition of a service plan")
  public String getEdition() {
    return edition;
  }

  public void setEdition(String edition) {
    this.edition = edition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicePlanInfo servicePlanInfo = (ServicePlanInfo) o;
    return Objects.equals(this.id, servicePlanInfo.id) &&
        Objects.equals(this.name, servicePlanInfo.name) &&
        Objects.equals(this.edition, servicePlanInfo.edition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, edition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicePlanInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    edition: ").append(toIndentedString(edition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

