/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DeliveryMode;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * SubscriptionInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class SubscriptionInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("eventFilters")
  private List<String> eventFilters = new ArrayList<String>();

  @SerializedName("expirationTime")
  private DateTime expirationTime = null;

  @SerializedName("expiresIn")
  private Integer expiresIn = null;

  /**
   * Subscription status
   */
  public enum StatusEnum {
    @SerializedName("Active")
    ACTIVE("Active"),
    
    @SerializedName("Suspended")
    SUSPENDED("Suspended");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("creationTime")
  private DateTime creationTime = null;

  @SerializedName("deliveryMode")
  private DeliveryMode deliveryMode = null;

  public SubscriptionInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of a subscription
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a subscription")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SubscriptionInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Canonical URI of a subscription
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Canonical URI of a subscription")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public SubscriptionInfo eventFilters(List<String> eventFilters) {
    this.eventFilters = eventFilters;
    return this;
  }

  public SubscriptionInfo addEventFiltersItem(String eventFiltersItem) {
    this.eventFilters.add(eventFiltersItem);
    return this;
  }

   /**
   * Collection of URIs to API resources (message-store/presence/detailed presence)
   * @return eventFilters
  **/
  @ApiModelProperty(example = "null", value = "Collection of URIs to API resources (message-store/presence/detailed presence)")
  public List<String> getEventFilters() {
    return eventFilters;
  }

  public void setEventFilters(List<String> eventFilters) {
    this.eventFilters = eventFilters;
  }

  public SubscriptionInfo expirationTime(DateTime expirationTime) {
    this.expirationTime = expirationTime;
    return this;
  }

   /**
   * Subscription expiration datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
   * @return expirationTime
  **/
  @ApiModelProperty(example = "null", value = "Subscription expiration datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z")
  public DateTime getExpirationTime() {
    return expirationTime;
  }

  public void setExpirationTime(DateTime expirationTime) {
    this.expirationTime = expirationTime;
  }

  public SubscriptionInfo expiresIn(Integer expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

   /**
   * Subscription lifetime in seconds. The default value is 900
   * @return expiresIn
  **/
  @ApiModelProperty(example = "null", value = "Subscription lifetime in seconds. The default value is 900")
  public Integer getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(Integer expiresIn) {
    this.expiresIn = expiresIn;
  }

  public SubscriptionInfo status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Subscription status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Subscription status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public SubscriptionInfo creationTime(DateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Subscription creation datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
   * @return creationTime
  **/
  @ApiModelProperty(example = "null", value = "Subscription creation datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z")
  public DateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(DateTime creationTime) {
    this.creationTime = creationTime;
  }

  public SubscriptionInfo deliveryMode(DeliveryMode deliveryMode) {
    this.deliveryMode = deliveryMode;
    return this;
  }

   /**
   * Delivery mode data
   * @return deliveryMode
  **/
  @ApiModelProperty(example = "null", value = "Delivery mode data")
  public DeliveryMode getDeliveryMode() {
    return deliveryMode;
  }

  public void setDeliveryMode(DeliveryMode deliveryMode) {
    this.deliveryMode = deliveryMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionInfo subscriptionInfo = (SubscriptionInfo) o;
    return Objects.equals(this.id, subscriptionInfo.id) &&
        Objects.equals(this.uri, subscriptionInfo.uri) &&
        Objects.equals(this.eventFilters, subscriptionInfo.eventFilters) &&
        Objects.equals(this.expirationTime, subscriptionInfo.expirationTime) &&
        Objects.equals(this.expiresIn, subscriptionInfo.expiresIn) &&
        Objects.equals(this.status, subscriptionInfo.status) &&
        Objects.equals(this.creationTime, subscriptionInfo.creationTime) &&
        Objects.equals(this.deliveryMode, subscriptionInfo.deliveryMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri, eventFilters, expirationTime, expiresIn, status, creationTime, deliveryMode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    eventFilters: ").append(toIndentedString(eventFilters)).append("\n");
    sb.append("    expirationTime: ").append(toIndentedString(expirationTime)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    deliveryMode: ").append(toIndentedString(deliveryMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

