/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * SyncInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class SyncInfo {
  /**
   * Type of synchronization
   */
  public enum SyncTypeEnum {
    @SerializedName("FSync")
    FSYNC("FSync"),
    
    @SerializedName("ISync")
    ISYNC("ISync");

    private String value;

    SyncTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("syncType")
  private SyncTypeEnum syncType = null;

  @SerializedName("syncToken")
  private String syncToken = null;

  @SerializedName("syncTime")
  private DateTime syncTime = null;

  public SyncInfo syncType(SyncTypeEnum syncType) {
    this.syncType = syncType;
    return this;
  }

   /**
   * Type of synchronization
   * @return syncType
  **/
  @ApiModelProperty(example = "null", value = "Type of synchronization")
  public SyncTypeEnum getSyncType() {
    return syncType;
  }

  public void setSyncType(SyncTypeEnum syncType) {
    this.syncType = syncType;
  }

  public SyncInfo syncToken(String syncToken) {
    this.syncToken = syncToken;
    return this;
  }

   /**
   * Synchronization token
   * @return syncToken
  **/
  @ApiModelProperty(example = "null", value = "Synchronization token")
  public String getSyncToken() {
    return syncToken;
  }

  public void setSyncToken(String syncToken) {
    this.syncToken = syncToken;
  }

  public SyncInfo syncTime(DateTime syncTime) {
    this.syncTime = syncTime;
    return this;
  }

   /**
   * Last synchronization datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
   * @return syncTime
  **/
  @ApiModelProperty(example = "null", value = "Last synchronization datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z")
  public DateTime getSyncTime() {
    return syncTime;
  }

  public void setSyncTime(DateTime syncTime) {
    this.syncTime = syncTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyncInfo syncInfo = (SyncInfo) o;
    return Objects.equals(this.syncType, syncInfo.syncType) &&
        Objects.equals(this.syncToken, syncInfo.syncToken) &&
        Objects.equals(this.syncTime, syncInfo.syncTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(syncType, syncToken, syncTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyncInfo {\n");
    
    sb.append("    syncType: ").append(toIndentedString(syncType)).append("\n");
    sb.append("    syncToken: ").append(toIndentedString(syncToken)).append("\n");
    sb.append("    syncTime: ").append(toIndentedString(syncTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

