/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TimezoneInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class TimezoneInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  public TimezoneInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Internal identifier of a timezone
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Internal identifier of a timezone")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TimezoneInfo uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Canonical URI of a timezone
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "Canonical URI of a timezone")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public TimezoneInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Short name of a timezone
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Short name of a timezone")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TimezoneInfo description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Meaningful description of the timezone
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "Meaningful description of the timezone")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimezoneInfo timezoneInfo = (TimezoneInfo) o;
    return Objects.equals(this.id, timezoneInfo.id) &&
        Objects.equals(this.uri, timezoneInfo.uri) &&
        Objects.equals(this.name, timezoneInfo.name) &&
        Objects.equals(this.description, timezoneInfo.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri, name, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimezoneInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

