/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserPermissionInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * UserPermission
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class UserPermission {
  @SerializedName("permission")
  private UserPermissionInfo permission = null;

  @SerializedName("scopes")
  private List<String> scopes = new ArrayList<String>();

  public UserPermission permission(UserPermissionInfo permission) {
    this.permission = permission;
    return this;
  }

   /**
   * Information on a permission granted
   * @return permission
  **/
  @ApiModelProperty(example = "null", value = "Information on a permission granted")
  public UserPermissionInfo getPermission() {
    return permission;
  }

  public void setPermission(UserPermissionInfo permission) {
    this.permission = permission;
  }

  public UserPermission scopes(List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public UserPermission addScopesItem(String scopesItem) {
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * List of active scopes for permission
   * @return scopes
  **/
  @ApiModelProperty(example = "null", value = "List of active scopes for permission")
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(List<String> scopes) {
    this.scopes = scopes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPermission userPermission = (UserPermission) o;
    return Objects.equals(this.permission, userPermission.permission) &&
        Objects.equals(this.scopes, userPermission.scopes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permission, scopes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPermission {\n");
    
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

