/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RecipientInfo;

/**
 * VoicemailInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class VoicemailInfo {
  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("recipient")
  private RecipientInfo recipient = null;

  public VoicemailInfo enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * If 'True' then voicemails are allowed to be received
   * @return enabled
  **/
  @ApiModelProperty(example = "null", value = "If 'True' then voicemails are allowed to be received")
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public VoicemailInfo recipient(RecipientInfo recipient) {
    this.recipient = recipient;
    return this;
  }

   /**
   * Recipient data
   * @return recipient
  **/
  @ApiModelProperty(example = "null", value = "Recipient data")
  public RecipientInfo getRecipient() {
    return recipient;
  }

  public void setRecipient(RecipientInfo recipient) {
    this.recipient = recipient;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoicemailInfo voicemailInfo = (VoicemailInfo) o;
    return Objects.equals(this.enabled, voicemailInfo.enabled) &&
        Objects.equals(this.recipient, voicemailInfo.recipient);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, recipient);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoicemailInfo {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    recipient: ").append(toIndentedString(recipient)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

