/*
 * RingCentral API
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TimeInterval;
import java.util.ArrayList;
import java.util.List;

/**
 * WeeklyScheduleInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:06:07.317Z")
public class WeeklyScheduleInfo {
  @SerializedName("monday")
  private List<TimeInterval> monday = new ArrayList<TimeInterval>();

  @SerializedName("tuesday")
  private List<TimeInterval> tuesday = new ArrayList<TimeInterval>();

  @SerializedName("wednesday")
  private List<TimeInterval> wednesday = new ArrayList<TimeInterval>();

  @SerializedName("thursday")
  private List<TimeInterval> thursday = new ArrayList<TimeInterval>();

  @SerializedName("friday")
  private List<TimeInterval> friday = new ArrayList<TimeInterval>();

  @SerializedName("saturday")
  private List<TimeInterval> saturday = new ArrayList<TimeInterval>();

  @SerializedName("sunday")
  private List<TimeInterval> sunday = new ArrayList<TimeInterval>();

  public WeeklyScheduleInfo monday(List<TimeInterval> monday) {
    this.monday = monday;
    return this;
  }

  public WeeklyScheduleInfo addMondayItem(TimeInterval mondayItem) {
    this.monday.add(mondayItem);
    return this;
  }

   /**
   * Time intervals for a particular day
   * @return monday
  **/
  @ApiModelProperty(example = "null", value = "Time intervals for a particular day")
  public List<TimeInterval> getMonday() {
    return monday;
  }

  public void setMonday(List<TimeInterval> monday) {
    this.monday = monday;
  }

  public WeeklyScheduleInfo tuesday(List<TimeInterval> tuesday) {
    this.tuesday = tuesday;
    return this;
  }

  public WeeklyScheduleInfo addTuesdayItem(TimeInterval tuesdayItem) {
    this.tuesday.add(tuesdayItem);
    return this;
  }

   /**
   * Time intervals for a particular day
   * @return tuesday
  **/
  @ApiModelProperty(example = "null", value = "Time intervals for a particular day")
  public List<TimeInterval> getTuesday() {
    return tuesday;
  }

  public void setTuesday(List<TimeInterval> tuesday) {
    this.tuesday = tuesday;
  }

  public WeeklyScheduleInfo wednesday(List<TimeInterval> wednesday) {
    this.wednesday = wednesday;
    return this;
  }

  public WeeklyScheduleInfo addWednesdayItem(TimeInterval wednesdayItem) {
    this.wednesday.add(wednesdayItem);
    return this;
  }

   /**
   * Time intervals for a particular day
   * @return wednesday
  **/
  @ApiModelProperty(example = "null", value = "Time intervals for a particular day")
  public List<TimeInterval> getWednesday() {
    return wednesday;
  }

  public void setWednesday(List<TimeInterval> wednesday) {
    this.wednesday = wednesday;
  }

  public WeeklyScheduleInfo thursday(List<TimeInterval> thursday) {
    this.thursday = thursday;
    return this;
  }

  public WeeklyScheduleInfo addThursdayItem(TimeInterval thursdayItem) {
    this.thursday.add(thursdayItem);
    return this;
  }

   /**
   * Time intervals for a particular day
   * @return thursday
  **/
  @ApiModelProperty(example = "null", value = "Time intervals for a particular day")
  public List<TimeInterval> getThursday() {
    return thursday;
  }

  public void setThursday(List<TimeInterval> thursday) {
    this.thursday = thursday;
  }

  public WeeklyScheduleInfo friday(List<TimeInterval> friday) {
    this.friday = friday;
    return this;
  }

  public WeeklyScheduleInfo addFridayItem(TimeInterval fridayItem) {
    this.friday.add(fridayItem);
    return this;
  }

   /**
   * Time intervals for a particular day
   * @return friday
  **/
  @ApiModelProperty(example = "null", value = "Time intervals for a particular day")
  public List<TimeInterval> getFriday() {
    return friday;
  }

  public void setFriday(List<TimeInterval> friday) {
    this.friday = friday;
  }

  public WeeklyScheduleInfo saturday(List<TimeInterval> saturday) {
    this.saturday = saturday;
    return this;
  }

  public WeeklyScheduleInfo addSaturdayItem(TimeInterval saturdayItem) {
    this.saturday.add(saturdayItem);
    return this;
  }

   /**
   * Time intervals for a particular day
   * @return saturday
  **/
  @ApiModelProperty(example = "null", value = "Time intervals for a particular day")
  public List<TimeInterval> getSaturday() {
    return saturday;
  }

  public void setSaturday(List<TimeInterval> saturday) {
    this.saturday = saturday;
  }

  public WeeklyScheduleInfo sunday(List<TimeInterval> sunday) {
    this.sunday = sunday;
    return this;
  }

  public WeeklyScheduleInfo addSundayItem(TimeInterval sundayItem) {
    this.sunday.add(sundayItem);
    return this;
  }

   /**
   * Time intervals for a particular day
   * @return sunday
  **/
  @ApiModelProperty(example = "null", value = "Time intervals for a particular day")
  public List<TimeInterval> getSunday() {
    return sunday;
  }

  public void setSunday(List<TimeInterval> sunday) {
    this.sunday = sunday;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeeklyScheduleInfo weeklyScheduleInfo = (WeeklyScheduleInfo) o;
    return Objects.equals(this.monday, weeklyScheduleInfo.monday) &&
        Objects.equals(this.tuesday, weeklyScheduleInfo.tuesday) &&
        Objects.equals(this.wednesday, weeklyScheduleInfo.wednesday) &&
        Objects.equals(this.thursday, weeklyScheduleInfo.thursday) &&
        Objects.equals(this.friday, weeklyScheduleInfo.friday) &&
        Objects.equals(this.saturday, weeklyScheduleInfo.saturday) &&
        Objects.equals(this.sunday, weeklyScheduleInfo.sunday);
  }

  @Override
  public int hashCode() {
    return Objects.hash(monday, tuesday, wednesday, thursday, friday, saturday, sunday);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeeklyScheduleInfo {\n");
    
    sb.append("    monday: ").append(toIndentedString(monday)).append("\n");
    sb.append("    tuesday: ").append(toIndentedString(tuesday)).append("\n");
    sb.append("    wednesday: ").append(toIndentedString(wednesday)).append("\n");
    sb.append("    thursday: ").append(toIndentedString(thursday)).append("\n");
    sb.append("    friday: ").append(toIndentedString(friday)).append("\n");
    sb.append("    saturday: ").append(toIndentedString(saturday)).append("\n");
    sb.append("    sunday: ").append(toIndentedString(sunday)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

